<html>

<head>
    <meta name=Title content="">
    <meta name=Keywords content="">
    <meta http-equiv=Content-Type content="text/html; charset=macintosh">
    <meta name=Generator content="Microsoft Word 14 (filtered)">
    <style>
        <!--
        /* Font Definitions */
        @font-face
        {font-family:Arial;
            panose-1:2 11 6 4 2 2 2 2 2 4;}
        @font-face
        {font-family:"Courier New";
            panose-1:2 7 3 9 2 2 5 2 4 4;}
        @font-face
        {font-family:Wingdings;
            panose-1:5 0 0 0 0 0 0 0 0 0;}
        @font-face
        {font-family:Verdana;
            panose-1:2 11 6 4 3 5 4 4 2 4;}
        @font-face
        {font-family:Verdana;
            panose-1:2 11 6 4 3 5 4 4 2 4;}
        @font-face
        {font-family:Calibri;
            panose-1:2 15 5 2 2 2 4 3 2 4;}
        @font-face
        {font-family:Cambria;
            panose-1:2 4 5 3 5 4 6 3 2 4;}
        @font-face
        {font-family:Tahoma;
            panose-1:2 11 6 4 3 5 4 4 2 4;}
        @font-face
        {font-family:"MS Mincho";}
        /* Style Definitions */
        p.MsoNormal, li.MsoNormal, div.MsoNormal
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        h1
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:12.0pt;
            margin-left:0in;
            text-indent:0in;
            font-size:12.0pt;
            font-family:"Times New Roman";
            color:black;
            font-weight:normal;}
        h2
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:12.0pt;
            margin-left:0in;
            text-indent:.5in;
            font-size:12.0pt;
            font-family:"Times New Roman";
            color:black;
            font-weight:normal;}
        h3
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:12.0pt;
            margin-left:0in;
            text-indent:1.0in;
            font-size:12.0pt;
            font-family:"Times New Roman";
            color:black;
            font-weight:normal;}
        h4
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:12.0pt;
            margin-left:0in;
            text-indent:1.5in;
            font-size:12.0pt;
            font-family:"Times New Roman";
            color:black;
            font-weight:normal;}
        h5
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:12.0pt;
            margin-left:0in;
            text-indent:2.0in;
            font-size:12.0pt;
            font-family:"Times New Roman";
            color:black;
            font-weight:normal;}
        h6
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:12.0pt;
            margin-left:0in;
            text-indent:2.5in;
            font-size:12.0pt;
            font-family:"Times New Roman";
            color:black;
            font-weight:normal;}
        p.MsoHeading7, li.MsoHeading7, div.MsoHeading7
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:12.0pt;
            margin-left:0in;
            text-indent:3.0in;
            font-size:12.0pt;
            font-family:"Times New Roman";
            color:black;}
        p.MsoHeading8, li.MsoHeading8, div.MsoHeading8
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:12.0pt;
            margin-left:0in;
            text-indent:3.5in;
            font-size:12.0pt;
            font-family:"Times New Roman";
            color:black;}
        p.MsoHeading9, li.MsoHeading9, div.MsoHeading9
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:12.0pt;
            margin-left:0in;
            text-indent:4.0in;
            font-size:12.0pt;
            font-family:"Times New Roman";
            color:black;}
        p.MsoIndex1, li.MsoIndex1, div.MsoIndex1
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:12.0pt;
            margin-bottom:.0001pt;
            text-indent:-12.0pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoIndex2, li.MsoIndex2, div.MsoIndex2
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:24.0pt;
            margin-bottom:.0001pt;
            text-indent:-12.0pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoIndex3, li.MsoIndex3, div.MsoIndex3
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:.5in;
            margin-bottom:.0001pt;
            text-indent:-12.0pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoIndex4, li.MsoIndex4, div.MsoIndex4
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:48.0pt;
            margin-bottom:.0001pt;
            text-indent:-12.0pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoIndex5, li.MsoIndex5, div.MsoIndex5
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:60.0pt;
            margin-bottom:.0001pt;
            text-indent:-12.0pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoIndex6, li.MsoIndex6, div.MsoIndex6
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:1.0in;
            margin-bottom:.0001pt;
            text-indent:-12.0pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoIndex7, li.MsoIndex7, div.MsoIndex7
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:84.0pt;
            margin-bottom:.0001pt;
            text-indent:-12.0pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoIndex8, li.MsoIndex8, div.MsoIndex8
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:96.0pt;
            margin-bottom:.0001pt;
            text-indent:-12.0pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoIndex9, li.MsoIndex9, div.MsoIndex9
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:1.5in;
            margin-bottom:.0001pt;
            text-indent:-12.0pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoToc1, li.MsoToc1, div.MsoToc1
        {margin-top:0in;
            margin-right:.2in;
            margin-bottom:12.0pt;
            margin-left:.5in;
            text-indent:-.5in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoToc2, li.MsoToc2, div.MsoToc2
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:12.0pt;
            margin-left:71.25pt;
            text-indent:-34.55pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoToc3, li.MsoToc3, div.MsoToc3
        {margin-top:0in;
            margin-right:.2in;
            margin-bottom:12.0pt;
            margin-left:1.5in;
            text-indent:-36.7pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoToc4, li.MsoToc4, div.MsoToc4
        {margin-top:0in;
            margin-right:.2in;
            margin-bottom:12.0pt;
            margin-left:2.0in;
            text-indent:-.5in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoToc5, li.MsoToc5, div.MsoToc5
        {margin-top:0in;
            margin-right:.2in;
            margin-bottom:12.0pt;
            margin-left:2.5in;
            text-indent:-.5in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoToc6, li.MsoToc6, div.MsoToc6
        {margin-top:0in;
            margin-right:.2in;
            margin-bottom:12.0pt;
            margin-left:3.0in;
            text-indent:-.5in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoToc7, li.MsoToc7, div.MsoToc7
        {margin-top:0in;
            margin-right:.2in;
            margin-bottom:12.0pt;
            margin-left:3.5in;
            text-indent:-.5in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoToc8, li.MsoToc8, div.MsoToc8
        {margin-top:0in;
            margin-right:.2in;
            margin-bottom:12.0pt;
            margin-left:3.5in;
            text-indent:-.5in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoToc9, li.MsoToc9, div.MsoToc9
        {margin-top:0in;
            margin-right:.2in;
            margin-bottom:12.0pt;
            margin-left:3.5in;
            text-indent:-.5in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoNormalIndent, li.MsoNormalIndent, div.MsoNormalIndent
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:.5in;
            margin-bottom:.0001pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoFootnoteText, li.MsoFootnoteText, div.MsoFootnoteText
        {margin:0in;
            margin-bottom:.0001pt;
            punctuation-wrap:simple;
            text-autospace:none;
            font-size:10.0pt;
            font-family:"Times New Roman";}
        p.MsoCommentText, li.MsoCommentText, div.MsoCommentText
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:10.0pt;
            font-family:"Times New Roman";}
        p.MsoHeader, li.MsoHeader, div.MsoHeader
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoFooter, li.MsoFooter, div.MsoFooter
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoIndexHeading, li.MsoIndexHeading, div.MsoIndexHeading
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:12.0pt;
            font-family:Cambria;
            font-weight:bold;}
        p.MsoCaption, li.MsoCaption, div.MsoCaption
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:10.0pt;
            font-family:"Times New Roman";
            font-weight:bold;}
        p.MsoTof, li.MsoTof, div.MsoTof
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoEnvelopeAddress, li.MsoEnvelopeAddress, div.MsoEnvelopeAddress
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:2.0in;
            margin-bottom:.0001pt;
            font-size:12.0pt;
            font-family:Cambria;}
        p.MsoEnvelopeReturn, li.MsoEnvelopeReturn, div.MsoEnvelopeReturn
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:10.0pt;
            font-family:Cambria;}
        span.MsoFootnoteReference
        {vertical-align:super;}
        p.MsoEndnoteText, li.MsoEndnoteText, div.MsoEndnoteText
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:10.0pt;
            font-family:"Times New Roman";}
        p.MsoToa, li.MsoToa, div.MsoToa
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:12.0pt;
            margin-bottom:.0001pt;
            text-indent:-12.0pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoMacroText, li.MsoMacroText, div.MsoMacroText
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:10.0pt;
            font-family:"Courier New";}
        p.MsoToaHeading, li.MsoToaHeading, div.MsoToaHeading
        {margin-top:6.0pt;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:0in;
            margin-bottom:.0001pt;
            font-size:12.0pt;
            font-family:Cambria;
            font-weight:bold;}
        p.MsoList, li.MsoList, div.MsoList
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:.25in;
            margin-bottom:.0001pt;
            text-indent:-.25in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoListBullet, li.MsoListBullet, div.MsoListBullet
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:12.0pt;
            margin-left:.5in;
            text-indent:-.5in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoListNumber, li.MsoListNumber, div.MsoListNumber
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:12.0pt;
            margin-left:.5in;
            text-indent:-.5in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoList2, li.MsoList2, div.MsoList2
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:.5in;
            margin-bottom:.0001pt;
            text-indent:-.25in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoList3, li.MsoList3, div.MsoList3
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:.75in;
            margin-bottom:.0001pt;
            text-indent:-.25in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoList4, li.MsoList4, div.MsoList4
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:1.0in;
            margin-bottom:.0001pt;
            text-indent:-.25in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoList5, li.MsoList5, div.MsoList5
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:1.25in;
            margin-bottom:.0001pt;
            text-indent:-.25in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoListBullet2, li.MsoListBullet2, div.MsoListBullet2
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:.5in;
            margin-bottom:.0001pt;
            text-indent:-.25in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoListBullet3, li.MsoListBullet3, div.MsoListBullet3
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:.75in;
            margin-bottom:.0001pt;
            text-indent:-.25in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoListBullet4, li.MsoListBullet4, div.MsoListBullet4
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:1.0in;
            margin-bottom:.0001pt;
            text-indent:-.25in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoListBullet5, li.MsoListBullet5, div.MsoListBullet5
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:1.25in;
            margin-bottom:.0001pt;
            text-indent:-.25in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoListNumber2, li.MsoListNumber2, div.MsoListNumber2
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:.5in;
            margin-bottom:.0001pt;
            text-indent:-.25in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoListNumber3, li.MsoListNumber3, div.MsoListNumber3
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:.75in;
            margin-bottom:.0001pt;
            text-indent:-.25in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoListNumber4, li.MsoListNumber4, div.MsoListNumber4
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:1.0in;
            margin-bottom:.0001pt;
            text-indent:-.25in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoListNumber5, li.MsoListNumber5, div.MsoListNumber5
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:1.25in;
            margin-bottom:.0001pt;
            text-indent:-.25in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoTitle, li.MsoTitle, div.MsoTitle
        {margin-top:12.0pt;
            margin-right:0in;
            margin-bottom:12.0pt;
            margin-left:0in;
            text-align:center;
            font-size:12.0pt;
            font-family:"Times New Roman";
            text-transform:uppercase;
            font-weight:bold;}
        p.MsoClosing, li.MsoClosing, div.MsoClosing
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:3.0in;
            margin-bottom:.0001pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoSignature, li.MsoSignature, div.MsoSignature
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:3.0in;
            margin-bottom:.0001pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoBodyText, li.MsoBodyText, div.MsoBodyText
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:12.0pt;
            margin-left:0in;
            text-indent:.5in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoBodyTextIndent, li.MsoBodyTextIndent, div.MsoBodyTextIndent
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:6.0pt;
            margin-left:.25in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoListContinue, li.MsoListContinue, div.MsoListContinue
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:6.0pt;
            margin-left:.25in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoListContinue2, li.MsoListContinue2, div.MsoListContinue2
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:6.0pt;
            margin-left:.5in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoListContinue3, li.MsoListContinue3, div.MsoListContinue3
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:6.0pt;
            margin-left:.75in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoListContinue4, li.MsoListContinue4, div.MsoListContinue4
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:6.0pt;
            margin-left:1.0in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoListContinue5, li.MsoListContinue5, div.MsoListContinue5
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:6.0pt;
            margin-left:1.25in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoMessageHeader, li.MsoMessageHeader, div.MsoMessageHeader
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:.75in;
            margin-bottom:.0001pt;
            text-indent:-.75in;
            background:#CCCCCC;
            border:none;
            padding:0in;
            font-size:12.0pt;
            font-family:Cambria;}
        p.MsoSubtitle, li.MsoSubtitle, div.MsoSubtitle
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:12.0pt;
            margin-left:0in;
            font-size:12.0pt;
            font-family:"Times New Roman";
            font-weight:bold;}
        p.MsoSalutation, li.MsoSalutation, div.MsoSalutation
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoDate, li.MsoDate, div.MsoDate
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoBodyTextFirstIndent, li.MsoBodyTextFirstIndent, div.MsoBodyTextFirstIndent
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:6.0pt;
            margin-left:0in;
            text-indent:10.5pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoBodyTextFirstIndent2, li.MsoBodyTextFirstIndent2, div.MsoBodyTextFirstIndent2
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:6.0pt;
            margin-left:.25in;
            text-indent:10.5pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoNoteHeading, li.MsoNoteHeading, div.MsoNoteHeading
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoBodyText2, li.MsoBodyText2, div.MsoBodyText2
        {margin:0in;
            margin-bottom:.0001pt;
            text-indent:.5in;
            line-height:200%;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoBodyText3, li.MsoBodyText3, div.MsoBodyText3
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:6.0pt;
            margin-left:0in;
            font-size:8.0pt;
            font-family:"Times New Roman";}
        p.MsoBodyTextIndent2, li.MsoBodyTextIndent2, div.MsoBodyTextIndent2
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:6.0pt;
            margin-left:.25in;
            line-height:200%;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoBodyTextIndent3, li.MsoBodyTextIndent3, div.MsoBodyTextIndent3
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:6.0pt;
            margin-left:.25in;
            font-size:8.0pt;
            font-family:"Times New Roman";}
        p.MsoBlockText, li.MsoBlockText, div.MsoBlockText
        {margin-top:0in;
            margin-right:1.0in;
            margin-bottom:6.0pt;
            margin-left:1.0in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        a:link, span.MsoHyperlink
        {color:blue;
            text-decoration:underline;}
        a:visited, span.MsoHyperlinkFollowed
        {color:purple;
            text-decoration:underline;}
        p.MsoDocumentMap, li.MsoDocumentMap, div.MsoDocumentMap
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:8.0pt;
            font-family:Tahoma;}
        p.MsoPlainText, li.MsoPlainText, div.MsoPlainText
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:10.0pt;
            font-family:"Courier New";}
        p.MsoAutoSig, li.MsoAutoSig, div.MsoAutoSig
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p
        {margin-right:0in;
            margin-left:0in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        address
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:12.0pt;
            font-family:"Times New Roman";
            font-style:italic;}
        pre
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:10.0pt;
            font-family:"Courier New";}
        p.MsoCommentSubject, li.MsoCommentSubject, div.MsoCommentSubject
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:10.0pt;
            font-family:"Times New Roman";
            font-weight:bold;}
        p.MsoAcetate, li.MsoAcetate, div.MsoAcetate
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:8.0pt;
            font-family:Tahoma;}
        p.MsoNoSpacing, li.MsoNoSpacing, div.MsoNoSpacing
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoListParagraph, li.MsoListParagraph, div.MsoListParagraph
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:.5in;
            margin-bottom:.0001pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoQuote, li.MsoQuote, div.MsoQuote
        {margin-top:0in;
            margin-right:1.0in;
            margin-bottom:12.0pt;
            margin-left:1.0in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoIntenseQuote, li.MsoIntenseQuote, div.MsoIntenseQuote
        {margin-top:10.0pt;
            margin-right:.65in;
            margin-bottom:14.0pt;
            margin-left:.65in;
            border:none;
            padding:0in;
            font-size:12.0pt;
            font-family:"Times New Roman";
            color:#4F81BD;
            font-weight:bold;
            font-style:italic;}
        p.MsoBibliography, li.MsoBibliography, div.MsoBibliography
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoTocHeading, li.MsoTocHeading, div.MsoTocHeading
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:12.0pt;
            margin-left:0in;
            text-align:center;
            font-size:12.0pt;
            font-family:"Times New Roman";
            font-weight:bold;}
        p.BodyTextContinued, li.BodyTextContinued, div.BodyTextContinued
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:12.0pt;
            margin-left:0in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        span.TitleChar
        {font-family:"Times New Roman";
            text-transform:uppercase;
            font-weight:bold;}
        span.SubtitleChar
        {font-family:"Times New Roman";
            font-weight:bold;}
        span.Heading1Char
        {font-family:"Times New Roman";
            color:black;}
        span.Heading2Char
        {font-family:"Times New Roman";
            color:black;}
        span.Heading3Char
        {font-family:"Times New Roman";
            color:black;}
        span.Heading4Char
        {font-family:"Times New Roman";
            color:black;}
        span.Heading5Char
        {font-family:"Times New Roman";
            color:black;}
        span.Heading6Char
        {font-family:"Times New Roman";
            color:black;}
        span.Heading7Char
        {font-family:"Times New Roman";
            color:black;}
        span.Heading8Char
        {font-family:"Times New Roman";
            color:black;}
        span.Heading9Char
        {font-family:"Times New Roman";
            color:black;}
        p.TOCPage, li.TOCPage, div.TOCPage
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:12.0pt;
            margin-left:0in;
            text-align:right;
            font-size:12.0pt;
            font-family:"Times New Roman";
            font-weight:bold;}
        p.TblText, li.TblText, div.TblText
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        span.sub1
        {font-family:Verdana;
            color:#565656;
            font-weight:bold;
            font-style:normal;}
        span.BalloonTextChar
        {font-family:Tahoma;}
        span.CommentSubjectChar
        {font-weight:bold;}
        span.DocumentMapChar
        {font-family:Tahoma;}
        span.HTMLAddressChar
        {font-style:italic;}
        span.HTMLPreformattedChar
        {font-family:"Courier New";}
        span.IntenseQuoteChar
        {color:#4F81BD;
            font-weight:bold;
            font-style:italic;}
        span.MacroTextChar
        {font-family:"Courier New";}
        span.MessageHeaderChar
        {font-family:Cambria;
            background:#CCCCCC;}
        span.PlainTextChar
        {font-family:"Courier New";}
        span.s7078511
        {font-family:Arial;}
        span.c14
        {color:#454440;}
        .MsoChpDefault
        {font-size:10.0pt;}
        /* Page Definitions */
        @page WordSection1
        {size:8.5in 11.0in;
            margin:.8in .8in .8in .9in;}
        div.WordSection1
        {page:WordSection1;}
        /* List Definitions */
        ol
        {margin-bottom:0in;}
        ul
        {margin-bottom:0in;}
        -->
    </style>

</head>

<body lang=EN-US link=blue vlink=purple>

<div class=WordSection1>

    <p class=MsoNormal align=center style='text-align:center'><b><span
                style='font-size:11.5pt;font-family:Calibri'>Cpyright</span></b></p>

    <p class=MsoNormal align=center style='text-align:center'><b><span
                style='font-size:11.5pt;font-family:Calibri'>Last Updated: February 10, 2017</span></b></p>

    <p class=MsoNormal><span style='font-size:11.0pt;font-family:Calibri'>&nbsp;</span></p>

    <p class=MsoNormal style='text-align:justify'><span style='font-size:11.0pt;
font-family:Calibri'>

Unless otherwise noted, content on this site Creative Commons Zero Qualification Statement (CC0) applies. This means that any form of reuse of the content of this site is permitted unless it is indicated that that part is a copyright exception applies to whether a particular item (such as a photo or document).

When reusing the content of this website attribution is not required. The Ministry of Defence suggests there price as in images (photo and video) named "Defense Ministry" as the source is indicated (unless otherwise stated). When citing the content should not be given the impression that the Ministry of Defense no longer supports the thrust of the derivative work.

The following rights are the Creative Commons Zero not changed declaration agreed and therefore remain in force:
<ul>
<li>Patent rights and trademark rights.</li>
<li>Rights of others, or parts of this website, or on how the site is used, such as publicity or privacy rights.</li>
</ul>
</span></p>

    <p class=MsoNormal style='text-align:justify'><span style='font-size:11.0pt;
font-family:Calibri'>&nbsp;</span></p>


</div>

</body>

</html>
