<html>

<head>
    <meta name=Title content="">
    <meta name=Keywords content="">
    <meta http-equiv=Content-Type content="text/html; charset=macintosh">
    <meta name=Generator content="Microsoft Word 14 (filtered)">
    <style>
        <!--
        /* Font Definitions */
        @font-face
        {font-family:Arial;
            panose-1:2 11 6 4 2 2 2 2 2 4;}
        @font-face
        {font-family:"Courier New";
            panose-1:2 7 3 9 2 2 5 2 4 4;}
        @font-face
        {font-family:Wingdings;
            panose-1:5 0 0 0 0 0 0 0 0 0;}
        @font-face
        {font-family:Verdana;
            panose-1:2 11 6 4 3 5 4 4 2 4;}
        @font-face
        {font-family:Verdana;
            panose-1:2 11 6 4 3 5 4 4 2 4;}
        @font-face
        {font-family:Calibri;
            panose-1:2 15 5 2 2 2 4 3 2 4;}
        @font-face
        {font-family:Cambria;
            panose-1:2 4 5 3 5 4 6 3 2 4;}
        @font-face
        {font-family:Tahoma;
            panose-1:2 11 6 4 3 5 4 4 2 4;}
        @font-face
        {font-family:"MS Mincho";}
        /* Style Definitions */
        p.MsoNormal, li.MsoNormal, div.MsoNormal
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        h1
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:12.0pt;
            margin-left:0in;
            text-indent:0in;
            font-size:12.0pt;
            font-family:"Times New Roman";
            color:black;
            font-weight:normal;}
        h2
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:12.0pt;
            margin-left:0in;
            text-indent:.5in;
            font-size:12.0pt;
            font-family:"Times New Roman";
            color:black;
            font-weight:normal;}
        h3
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:12.0pt;
            margin-left:0in;
            text-indent:1.0in;
            font-size:12.0pt;
            font-family:"Times New Roman";
            color:black;
            font-weight:normal;}
        h4
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:12.0pt;
            margin-left:0in;
            text-indent:1.5in;
            font-size:12.0pt;
            font-family:"Times New Roman";
            color:black;
            font-weight:normal;}
        h5
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:12.0pt;
            margin-left:0in;
            text-indent:2.0in;
            font-size:12.0pt;
            font-family:"Times New Roman";
            color:black;
            font-weight:normal;}
        h6
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:12.0pt;
            margin-left:0in;
            text-indent:2.5in;
            font-size:12.0pt;
            font-family:"Times New Roman";
            color:black;
            font-weight:normal;}
        p.MsoHeading7, li.MsoHeading7, div.MsoHeading7
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:12.0pt;
            margin-left:0in;
            text-indent:3.0in;
            font-size:12.0pt;
            font-family:"Times New Roman";
            color:black;}
        p.MsoHeading8, li.MsoHeading8, div.MsoHeading8
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:12.0pt;
            margin-left:0in;
            text-indent:3.5in;
            font-size:12.0pt;
            font-family:"Times New Roman";
            color:black;}
        p.MsoHeading9, li.MsoHeading9, div.MsoHeading9
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:12.0pt;
            margin-left:0in;
            text-indent:4.0in;
            font-size:12.0pt;
            font-family:"Times New Roman";
            color:black;}
        p.MsoIndex1, li.MsoIndex1, div.MsoIndex1
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:12.0pt;
            margin-bottom:.0001pt;
            text-indent:-12.0pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoIndex2, li.MsoIndex2, div.MsoIndex2
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:24.0pt;
            margin-bottom:.0001pt;
            text-indent:-12.0pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoIndex3, li.MsoIndex3, div.MsoIndex3
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:.5in;
            margin-bottom:.0001pt;
            text-indent:-12.0pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoIndex4, li.MsoIndex4, div.MsoIndex4
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:48.0pt;
            margin-bottom:.0001pt;
            text-indent:-12.0pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoIndex5, li.MsoIndex5, div.MsoIndex5
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:60.0pt;
            margin-bottom:.0001pt;
            text-indent:-12.0pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoIndex6, li.MsoIndex6, div.MsoIndex6
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:1.0in;
            margin-bottom:.0001pt;
            text-indent:-12.0pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoIndex7, li.MsoIndex7, div.MsoIndex7
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:84.0pt;
            margin-bottom:.0001pt;
            text-indent:-12.0pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoIndex8, li.MsoIndex8, div.MsoIndex8
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:96.0pt;
            margin-bottom:.0001pt;
            text-indent:-12.0pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoIndex9, li.MsoIndex9, div.MsoIndex9
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:1.5in;
            margin-bottom:.0001pt;
            text-indent:-12.0pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoToc1, li.MsoToc1, div.MsoToc1
        {margin-top:0in;
            margin-right:.2in;
            margin-bottom:12.0pt;
            margin-left:.5in;
            text-indent:-.5in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoToc2, li.MsoToc2, div.MsoToc2
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:12.0pt;
            margin-left:71.25pt;
            text-indent:-34.55pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoToc3, li.MsoToc3, div.MsoToc3
        {margin-top:0in;
            margin-right:.2in;
            margin-bottom:12.0pt;
            margin-left:1.5in;
            text-indent:-36.7pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoToc4, li.MsoToc4, div.MsoToc4
        {margin-top:0in;
            margin-right:.2in;
            margin-bottom:12.0pt;
            margin-left:2.0in;
            text-indent:-.5in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoToc5, li.MsoToc5, div.MsoToc5
        {margin-top:0in;
            margin-right:.2in;
            margin-bottom:12.0pt;
            margin-left:2.5in;
            text-indent:-.5in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoToc6, li.MsoToc6, div.MsoToc6
        {margin-top:0in;
            margin-right:.2in;
            margin-bottom:12.0pt;
            margin-left:3.0in;
            text-indent:-.5in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoToc7, li.MsoToc7, div.MsoToc7
        {margin-top:0in;
            margin-right:.2in;
            margin-bottom:12.0pt;
            margin-left:3.5in;
            text-indent:-.5in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoToc8, li.MsoToc8, div.MsoToc8
        {margin-top:0in;
            margin-right:.2in;
            margin-bottom:12.0pt;
            margin-left:3.5in;
            text-indent:-.5in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoToc9, li.MsoToc9, div.MsoToc9
        {margin-top:0in;
            margin-right:.2in;
            margin-bottom:12.0pt;
            margin-left:3.5in;
            text-indent:-.5in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoNormalIndent, li.MsoNormalIndent, div.MsoNormalIndent
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:.5in;
            margin-bottom:.0001pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoFootnoteText, li.MsoFootnoteText, div.MsoFootnoteText
        {margin:0in;
            margin-bottom:.0001pt;
            punctuation-wrap:simple;
            text-autospace:none;
            font-size:10.0pt;
            font-family:"Times New Roman";}
        p.MsoCommentText, li.MsoCommentText, div.MsoCommentText
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:10.0pt;
            font-family:"Times New Roman";}
        p.MsoHeader, li.MsoHeader, div.MsoHeader
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoFooter, li.MsoFooter, div.MsoFooter
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoIndexHeading, li.MsoIndexHeading, div.MsoIndexHeading
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:12.0pt;
            font-family:Cambria;
            font-weight:bold;}
        p.MsoCaption, li.MsoCaption, div.MsoCaption
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:10.0pt;
            font-family:"Times New Roman";
            font-weight:bold;}
        p.MsoTof, li.MsoTof, div.MsoTof
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoEnvelopeAddress, li.MsoEnvelopeAddress, div.MsoEnvelopeAddress
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:2.0in;
            margin-bottom:.0001pt;
            font-size:12.0pt;
            font-family:Cambria;}
        p.MsoEnvelopeReturn, li.MsoEnvelopeReturn, div.MsoEnvelopeReturn
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:10.0pt;
            font-family:Cambria;}
        span.MsoFootnoteReference
        {vertical-align:super;}
        p.MsoEndnoteText, li.MsoEndnoteText, div.MsoEndnoteText
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:10.0pt;
            font-family:"Times New Roman";}
        p.MsoToa, li.MsoToa, div.MsoToa
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:12.0pt;
            margin-bottom:.0001pt;
            text-indent:-12.0pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoMacroText, li.MsoMacroText, div.MsoMacroText
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:10.0pt;
            font-family:"Courier New";}
        p.MsoToaHeading, li.MsoToaHeading, div.MsoToaHeading
        {margin-top:6.0pt;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:0in;
            margin-bottom:.0001pt;
            font-size:12.0pt;
            font-family:Cambria;
            font-weight:bold;}
        p.MsoList, li.MsoList, div.MsoList
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:.25in;
            margin-bottom:.0001pt;
            text-indent:-.25in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoListBullet, li.MsoListBullet, div.MsoListBullet
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:12.0pt;
            margin-left:.5in;
            text-indent:-.5in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoListNumber, li.MsoListNumber, div.MsoListNumber
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:12.0pt;
            margin-left:.5in;
            text-indent:-.5in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoList2, li.MsoList2, div.MsoList2
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:.5in;
            margin-bottom:.0001pt;
            text-indent:-.25in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoList3, li.MsoList3, div.MsoList3
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:.75in;
            margin-bottom:.0001pt;
            text-indent:-.25in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoList4, li.MsoList4, div.MsoList4
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:1.0in;
            margin-bottom:.0001pt;
            text-indent:-.25in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoList5, li.MsoList5, div.MsoList5
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:1.25in;
            margin-bottom:.0001pt;
            text-indent:-.25in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoListBullet2, li.MsoListBullet2, div.MsoListBullet2
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:.5in;
            margin-bottom:.0001pt;
            text-indent:-.25in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoListBullet3, li.MsoListBullet3, div.MsoListBullet3
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:.75in;
            margin-bottom:.0001pt;
            text-indent:-.25in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoListBullet4, li.MsoListBullet4, div.MsoListBullet4
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:1.0in;
            margin-bottom:.0001pt;
            text-indent:-.25in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoListBullet5, li.MsoListBullet5, div.MsoListBullet5
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:1.25in;
            margin-bottom:.0001pt;
            text-indent:-.25in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoListNumber2, li.MsoListNumber2, div.MsoListNumber2
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:.5in;
            margin-bottom:.0001pt;
            text-indent:-.25in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoListNumber3, li.MsoListNumber3, div.MsoListNumber3
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:.75in;
            margin-bottom:.0001pt;
            text-indent:-.25in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoListNumber4, li.MsoListNumber4, div.MsoListNumber4
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:1.0in;
            margin-bottom:.0001pt;
            text-indent:-.25in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoListNumber5, li.MsoListNumber5, div.MsoListNumber5
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:1.25in;
            margin-bottom:.0001pt;
            text-indent:-.25in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoTitle, li.MsoTitle, div.MsoTitle
        {margin-top:12.0pt;
            margin-right:0in;
            margin-bottom:12.0pt;
            margin-left:0in;
            text-align:center;
            font-size:12.0pt;
            font-family:"Times New Roman";
            text-transform:uppercase;
            font-weight:bold;}
        p.MsoClosing, li.MsoClosing, div.MsoClosing
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:3.0in;
            margin-bottom:.0001pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoSignature, li.MsoSignature, div.MsoSignature
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:3.0in;
            margin-bottom:.0001pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoBodyText, li.MsoBodyText, div.MsoBodyText
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:12.0pt;
            margin-left:0in;
            text-indent:.5in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoBodyTextIndent, li.MsoBodyTextIndent, div.MsoBodyTextIndent
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:6.0pt;
            margin-left:.25in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoListContinue, li.MsoListContinue, div.MsoListContinue
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:6.0pt;
            margin-left:.25in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoListContinue2, li.MsoListContinue2, div.MsoListContinue2
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:6.0pt;
            margin-left:.5in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoListContinue3, li.MsoListContinue3, div.MsoListContinue3
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:6.0pt;
            margin-left:.75in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoListContinue4, li.MsoListContinue4, div.MsoListContinue4
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:6.0pt;
            margin-left:1.0in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoListContinue5, li.MsoListContinue5, div.MsoListContinue5
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:6.0pt;
            margin-left:1.25in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoMessageHeader, li.MsoMessageHeader, div.MsoMessageHeader
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:.75in;
            margin-bottom:.0001pt;
            text-indent:-.75in;
            background:#CCCCCC;
            border:none;
            padding:0in;
            font-size:12.0pt;
            font-family:Cambria;}
        p.MsoSubtitle, li.MsoSubtitle, div.MsoSubtitle
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:12.0pt;
            margin-left:0in;
            font-size:12.0pt;
            font-family:"Times New Roman";
            font-weight:bold;}
        p.MsoSalutation, li.MsoSalutation, div.MsoSalutation
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoDate, li.MsoDate, div.MsoDate
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoBodyTextFirstIndent, li.MsoBodyTextFirstIndent, div.MsoBodyTextFirstIndent
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:6.0pt;
            margin-left:0in;
            text-indent:10.5pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoBodyTextFirstIndent2, li.MsoBodyTextFirstIndent2, div.MsoBodyTextFirstIndent2
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:6.0pt;
            margin-left:.25in;
            text-indent:10.5pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoNoteHeading, li.MsoNoteHeading, div.MsoNoteHeading
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoBodyText2, li.MsoBodyText2, div.MsoBodyText2
        {margin:0in;
            margin-bottom:.0001pt;
            text-indent:.5in;
            line-height:200%;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoBodyText3, li.MsoBodyText3, div.MsoBodyText3
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:6.0pt;
            margin-left:0in;
            font-size:8.0pt;
            font-family:"Times New Roman";}
        p.MsoBodyTextIndent2, li.MsoBodyTextIndent2, div.MsoBodyTextIndent2
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:6.0pt;
            margin-left:.25in;
            line-height:200%;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoBodyTextIndent3, li.MsoBodyTextIndent3, div.MsoBodyTextIndent3
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:6.0pt;
            margin-left:.25in;
            font-size:8.0pt;
            font-family:"Times New Roman";}
        p.MsoBlockText, li.MsoBlockText, div.MsoBlockText
        {margin-top:0in;
            margin-right:1.0in;
            margin-bottom:6.0pt;
            margin-left:1.0in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        a:link, span.MsoHyperlink
        {color:blue;
            text-decoration:underline;}
        a:visited, span.MsoHyperlinkFollowed
        {color:purple;
            text-decoration:underline;}
        p.MsoDocumentMap, li.MsoDocumentMap, div.MsoDocumentMap
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:8.0pt;
            font-family:Tahoma;}
        p.MsoPlainText, li.MsoPlainText, div.MsoPlainText
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:10.0pt;
            font-family:"Courier New";}
        p.MsoAutoSig, li.MsoAutoSig, div.MsoAutoSig
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p
        {margin-right:0in;
            margin-left:0in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        address
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:12.0pt;
            font-family:"Times New Roman";
            font-style:italic;}
        pre
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:10.0pt;
            font-family:"Courier New";}
        p.MsoCommentSubject, li.MsoCommentSubject, div.MsoCommentSubject
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:10.0pt;
            font-family:"Times New Roman";
            font-weight:bold;}
        p.MsoAcetate, li.MsoAcetate, div.MsoAcetate
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:8.0pt;
            font-family:Tahoma;}
        p.MsoNoSpacing, li.MsoNoSpacing, div.MsoNoSpacing
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoListParagraph, li.MsoListParagraph, div.MsoListParagraph
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:.5in;
            margin-bottom:.0001pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoQuote, li.MsoQuote, div.MsoQuote
        {margin-top:0in;
            margin-right:1.0in;
            margin-bottom:12.0pt;
            margin-left:1.0in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoIntenseQuote, li.MsoIntenseQuote, div.MsoIntenseQuote
        {margin-top:10.0pt;
            margin-right:.65in;
            margin-bottom:14.0pt;
            margin-left:.65in;
            border:none;
            padding:0in;
            font-size:12.0pt;
            font-family:"Times New Roman";
            color:#4F81BD;
            font-weight:bold;
            font-style:italic;}
        p.MsoBibliography, li.MsoBibliography, div.MsoBibliography
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        p.MsoTocHeading, li.MsoTocHeading, div.MsoTocHeading
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:12.0pt;
            margin-left:0in;
            text-align:center;
            font-size:12.0pt;
            font-family:"Times New Roman";
            font-weight:bold;}
        p.BodyTextContinued, li.BodyTextContinued, div.BodyTextContinued
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:12.0pt;
            margin-left:0in;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        span.TitleChar
        {font-family:"Times New Roman";
            text-transform:uppercase;
            font-weight:bold;}
        span.SubtitleChar
        {font-family:"Times New Roman";
            font-weight:bold;}
        span.Heading1Char
        {font-family:"Times New Roman";
            color:black;}
        span.Heading2Char
        {font-family:"Times New Roman";
            color:black;}
        span.Heading3Char
        {font-family:"Times New Roman";
            color:black;}
        span.Heading4Char
        {font-family:"Times New Roman";
            color:black;}
        span.Heading5Char
        {font-family:"Times New Roman";
            color:black;}
        span.Heading6Char
        {font-family:"Times New Roman";
            color:black;}
        span.Heading7Char
        {font-family:"Times New Roman";
            color:black;}
        span.Heading8Char
        {font-family:"Times New Roman";
            color:black;}
        span.Heading9Char
        {font-family:"Times New Roman";
            color:black;}
        p.TOCPage, li.TOCPage, div.TOCPage
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:12.0pt;
            margin-left:0in;
            text-align:right;
            font-size:12.0pt;
            font-family:"Times New Roman";
            font-weight:bold;}
        p.TblText, li.TblText, div.TblText
        {margin:0in;
            margin-bottom:.0001pt;
            font-size:12.0pt;
            font-family:"Times New Roman";}
        span.sub1
        {font-family:Verdana;
            color:#565656;
            font-weight:bold;
            font-style:normal;}
        span.BalloonTextChar
        {font-family:Tahoma;}
        span.CommentSubjectChar
        {font-weight:bold;}
        span.DocumentMapChar
        {font-family:Tahoma;}
        span.HTMLAddressChar
        {font-style:italic;}
        span.HTMLPreformattedChar
        {font-family:"Courier New";}
        span.IntenseQuoteChar
        {color:#4F81BD;
            font-weight:bold;
            font-style:italic;}
        span.MacroTextChar
        {font-family:"Courier New";}
        span.MessageHeaderChar
        {font-family:Cambria;
            background:#CCCCCC;}
        span.PlainTextChar
        {font-family:"Courier New";}
        span.s7078511
        {font-family:Arial;}
        span.c14
        {color:#454440;}
        .MsoChpDefault
        {font-size:10.0pt;}
        /* Page Definitions */
        @page WordSection1
        {size:8.5in 11.0in;
            margin:.8in .8in .8in .9in;}
        div.WordSection1
        {page:WordSection1;}
        /* List Definitions */
        ol
        {margin-bottom:0in;}
        ul
        {margin-bottom:0in;}
        -->
    </style>

</head>

<body lang=EN-US link=blue vlink=purple>

<div class=WordSection1>

    <p class=MsoNormal align=center style='text-align:center'><b><span
                style='font-size:11.5pt;font-family:Calibri'>Terms of Service</span></b></p>

    <p class=MsoNormal align=center style='text-align:center'><b><span
                style='font-size:11.5pt;font-family:Calibri'>Last Updated: February 10, 2017</span></b></p>

    <p class=MsoNormal><span style='font-size:11.0pt;font-family:Calibri'>&nbsp;</span></p>

    <p class=MsoNormal style='text-align:justify'><span style='font-size:11.0pt;
font-family:Calibri'>Welcome to the SamsaSoftware, LLC ("<b>SamsaSoftware</b>")
website located at </span><a href="http://samsasoftware.nl/"><span style='font-size:
11.0pt;font-family:Calibri'>http://samsasoftware.nl/</span></a><span
            style='font-size:11.0pt;font-family:Calibri'> (the <b><i>Site</i></b>). Please
read these Terms of Service (these "<b>Terms</b>") carefully because they
govern your use of our Site and our child care management-related services accessible
via our Site and our mobile device application ("<b>App</b>"). To make these
Terms easier to read, the Site, such services and App are collectively called
the "<b>Services</b>."</span></p>

    <p class=MsoNormal style='text-align:justify'><span style='font-size:11.0pt;
font-family:Calibri'>&nbsp;</span></p>

    <p class=MsoNormal style='text-align:justify'><b><span style='font-family:Calibri'>Agreement
to Terms</span></b></p>

    <p class=MsoNormal style='text-align:justify'><span style='font-size:11.0pt;
font-family:Calibri'>By using our Services, you agree to be bound by these
Terms, unless we have entered into a separate written agreement. If you don't agree
to these Terms, do not use the Services.</span></p>

    <p class=MsoNormal style='text-align:justify'><span style='font-size:11.0pt;
font-family:Calibri'>&nbsp;</span></p>

    <p class=MsoNormal style='text-align:justify'><b><span style='font-family:Calibri'>Changes
to Terms or Services</span></b></p>

    <p class=MsoNormal style='text-align:justify'><span style='font-size:11.0pt;
font-family:Calibri'>We may modify the Terms at any time, in our sole
discretion. If we do so, we'll let you know either by posting the modified
Terms on the Site, via the App or through other communications. It's important that
you review the Terms whenever we modify them because if you continue to</span><span
            style='font-size:11.0pt;font-family:Calibri'> use the Services after we have
posted the modified Terms on the Site or via the App</span><span
            style='font-size:11.0pt;font-family:Calibri'>, you are indicating to us that
you </span><span style='font-size:11.0pt;font-family:Calibri'>agree to be bound
by the modified Terms. If you don't agree to be bound by the modified Terms, then
you may not use the Services anymore. Because our Services are evolving over
time we may change or discontinue all or any part of the Services, at any time
and without notice, at our sole discretion.</span></p>

    <p style='margin:0in;margin-bottom:.0001pt'><span style='font-size:11.0pt;
font-family:Calibri'>&nbsp;</span></p>

    <p class=MsoNormal style='margin-bottom:6.0pt'><b><span style='font-family:
Calibri'>Who May Use the Services</span></b></p>

    <p class=MsoNormal><u><span style='font-size:11.5pt;font-family:Calibri'>Eligibility</span></u></p>

    <p style='margin-top:0in;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;
text-align:justify'><span style='font-size:11.0pt;font-family:Calibri'>You may
use the Services only if you are 18 years or older and capable of forming a
binding contract with SamsaSoftware and are not barred from using the Services
under applicable law.</span></p>

    <p class=MsoNormal><u><span style='font-size:11.5pt;font-family:Calibri'>Registration
and Your Information</span></u></p>

    <p style='margin:0in;margin-bottom:.0001pt;text-align:justify'><span
            style='font-size:11.0pt;font-family:Calibri'>If you want to use certain
features of the </span><span style='font-size:11.0pt;font-family:Calibri'>Services
</span><span style='font-size:11.0pt;font-family:Calibri'>you'll have to create
an account </span><span style='font-size:11.0pt;font-family:Calibri'>("<b>Account</b>").
</span><span style='font-size:11.0pt;font-family:Calibri'>You can do this via
the Site or App. </span></p>

    <p style='margin:0in;margin-bottom:.0001pt;text-align:justify'><span
            style='font-size:11.0pt;font-family:Calibri'>&nbsp;</span></p>

    <p style='margin:0in;margin-bottom:.0001pt;text-align:justify'><span
            style='font-size:11.0pt;font-family:Calibri'>It's important that you provide us
with accurate, complete and up-to-date information for your Account and you
agree to update such </span><span style='font-size:11.0pt;font-family:Calibri'>information,
as needed, to keep it accurate, complete and up-to-date. If you don't, we might
have to suspend or terminate your Account. You agree that you won't disclose
your Account password to anyone and you'll notify us immediately of any unauthorized
use of your Account. You're responsible for all activities that occur under
your Account, whether or not you know about them.&nbsp; </span></p>

    <p style='margin:0in;margin-bottom:.0001pt;text-align:justify'><span
            style='font-size:11.0pt;font-family:Calibri'>&nbsp;</span></p>

    <p class=MsoNormal style='text-align:justify'><b><span style='font-family:Calibri'>Privacy
Policy</span></b></p>

    <p class=MsoNormal style='text-align:justify'><span style='font-size:11.0pt;
font-family:Calibri'>Please refer to our Privacy Policy (</span><a
            href="https://production.samsasoftware.com/terms/privacy"><span style='font-size:11.0pt;
font-family:Calibri'>https://production.samsasoftware.com/terms/privacy</span></a><span
            style='font-size:11.0pt;font-family:Calibri'>) for information on how we
collect, use and disclose information from our users and how to request the
deletion of certain information.</span></p>

    <p class=MsoNormal style='text-align:justify'><span style='font-size:11.0pt;
font-family:Calibri'>&nbsp;</span></p>

    <p class=MsoNormal style='text-align:justify'><b><span lang=EN
                                                           style='font-family:Calibri'>Feedback</span></b></p>

    <p class=MsoNormal style='text-align:justify'><span style='font-size:11.0pt;
font-family:Calibri'>We welcome feedback, comments and suggestions for
improvements to the Services ("<b>Feedback</b>"). You can submit Feedback at
any time, including by emailing us at </span><a href="mailto:info@samsasoftware.nl"><span
                style='font-size:11.0pt;font-family:Calibri'>info@samsasoftware.nl</span></a><span
            style='font-size:11.0pt;font-family:Calibri'>. You grant to us a non</span><span
            style='font-size:11.0pt;font-family:Calibri'>-exclusive, worldwide, perpetual,
irrevocable, fully-paid, royalty-free, sublicensable and transferable license
under any and all intellectual property rights that you own or control to use,
copy, modify, create derivative works based upon and otherwise exploit the
Feedback for any purpose.</span></p>

    <p class=MsoNormal style='text-align:justify'><span lang=EN style='font-size:
11.0pt;font-family:Calibri'>&nbsp;</span></p>

    <p class=MsoNormal style='text-align:justify'><b><span style='font-family:Calibri'>Content
and Content Rights</span></b></p>

    <p class=MsoNormal style='text-align:justify'><span style='font-size:11.0pt;
font-family:Calibri'>For purposes of these Terms: (i) "<b>Content</b>" means </span><span
            style='font-size:11.0pt;font-family:Calibri'>text, graphics, images, music,
software, audio, video, works of authorship of any kind, and information or
other materials that are posted, generated, provided or otherwise made
available through the Services; and (ii) "<b>User Content</b>" means any
Content that Account holders (including you) provide to be made available
through the Services. Content includes without limitation User Content.</span></p>

    <p class=MsoNormal style='text-align:justify'><span style='font-size:11.0pt;
font-family:Calibri'>&nbsp;</span></p>

    <p class=MsoNormal style='text-align:justify'><b><span style='font-family:Calibri'>Content
Ownership, Responsibility and Removal</span></b></p>

    <p class=MsoNormal style='text-align:justify'><span style='font-size:11.0pt;
font-family:Calibri'>SamsaSoftware does not claim any ownership rights in any User Content
and nothing in these Terms will be deemed to restrict any rights that you may
have to use and exploit your User Content. Subject to the foregoing, SamsaSoftware
and its licensors exclusively own all right, title and interest in and to the
Services and Content, including all associated intellectual property rights. You
acknowledge that the Services and Content are protected by copyright,
trademark, and other laws of the United States and foreign countries. You agree
not to remove, alter or obscure any copyright, trademark, service mark or other
proprietary rights notices incorporated in or accompanying the Services or Content.</span></p>

    <p class=MsoNormal style='text-align:justify'><span style='font-size:11.0pt;
font-family:Calibri'>&nbsp;</span></p>

    <p class=MsoNormal style='text-align:justify'><u><span style='font-size:11.5pt;
font-family:Calibri'>Rights in User Content Granted by You</span></u></p>

    <p class=MsoNormal style='text-align:justify'><span style='font-size:11.0pt;
font-family:Calibri'>By making any User Content available through Services you hereby
grant to SamsaSoftware a non-exclusive, transferable, sublicenseable, worldwide, royalty-free
license to use, copy, modify, create derivative works based upon, distribute,
publicly display, publicly perform and distribute your User Content in
connection with </span><span lang=EN style='font-size:11.0pt;font-family:Calibri'>operating
and providing the Services and Content to you and to other Account holders.&nbsp;
</span></p>

    <p class=MsoNormal style='text-align:justify'><span style='font-size:11.0pt;
font-family:Calibri'>&nbsp;</span></p>

    <p class=MsoNormal style='text-align:justify'><span style='font-size:11.0pt;
font-family:Calibri'>You are solely responsible for all your User Content. You
represent and warrant that <span class=sub1><span style='font-family:Calibri;
color:windowtext;font-weight:normal'>you own all your User Content or you have
all rights that are necessary to grant us the license rights in your User
Content under these Terms. You also represent and warrant that neither </span></span>your
User Content, nor your use and provision of your User Content to be made
available through the Services, nor any use of your User Content by SamsaSoftware on
</span><span style='font-size:11.0pt;font-family:Calibri'>or through the
Services will infringe, misappropriate or violate a third party's intellectual
property rights, or rights of publicity or privacy, or result in the violation
of any applicable law or regulation.</span></p>

    <p style='margin:0in;margin-bottom:.0001pt;text-align:justify'><span
            style='font-size:11.0pt;font-family:Calibri'>&nbsp;</span></p>

    <p style='margin:0in;margin-bottom:.0001pt;text-align:justify'><span
            style='font-size:11.0pt;font-family:Calibri'>You can remove your User Content by
specifically deleting it. However, in certain instances, some of your User Content
(such as posts or comments you make) may not be completely removed and copies
of your User Content may continue to exist on the Services. We are not
responsible or liable for the removal or deletion of (or the failure to remove
or delete) any of your User Content.</span></p>

    <p style='margin:0in;margin-bottom:.0001pt;text-align:justify'><u><span
                style='font-size:11.0pt;font-family:Calibri'><span style='text-decoration:none'>&nbsp;</span></span></u></p>

    <p style='margin:0in;margin-bottom:.0001pt;text-align:justify'><u><span
                style='font-size:11.5pt;font-family:Calibri'>Rights in Content Granted by SamsaSoftware</span></u></p>

    <p style='margin:0in;margin-bottom:.0001pt;text-align:justify'><span
            style='font-size:11.0pt;font-family:Calibri'>Subject to your compliance with
these Terms, SamsaSoftware grants you a limited, non-exclusive, non-transferable,
non-sublicensable license to download, view, copy, display and print the
Content solely in connection with your permitted use of the Services and solely
for your personal and non-commercial purposes.</span></p>

    <p style='margin:0in;margin-bottom:.0001pt;text-align:justify'><b><span
                style='font-family:Calibri'>&nbsp;</span></b></p>

    <p style='margin:0in;margin-bottom:.0001pt;text-align:justify'><b><span
                style='font-family:Calibri'>Rights in App Granted by SamsaSoftware</span></b></p>

    <p style='margin:0in;margin-bottom:.0001pt;text-align:justify'><span
            style='font-size:11.0pt;font-family:Calibri'>Subject</span><span
            style='font-size:11.0pt;font-family:Calibri'> to </span><span style='font-size:
11.0pt;font-family:Calibri'>your </span><span style='font-size:11.0pt;
font-family:Calibri'>compliance with these Terms, </span><span
            style='font-size:11.0pt;font-family:Calibri'>SamsaSoftware grants you a limited
non-exclusive, non-transferable, non-sublicenseable license to </span><span
            style='font-size:11.0pt;font-family:Calibri'>download </span><span
            style='font-size:11.0pt;font-family:Calibri'>and </span><span style='font-size:
11.0pt;font-family:Calibri'>install </span><span style='font-size:11.0pt;
font-family:Calibri'>a copy of the App </span><span style='font-size:11.0pt;
font-family:Calibri'>on </span><span style='font-size:11.0pt;font-family:Calibri'>a
mobile</span><span style='font-size:11.0pt;font-family:Calibri'> device </span><span
            style='font-size:11.0pt;font-family:Calibri'>or computer </span><span
            style='font-size:11.0pt;font-family:Calibri'>that </span><span
            style='font-size:11.0pt;font-family:Calibri'>you own or control and </span><span
            style='font-size:11.0pt;font-family:Calibri'>to </span><span style='font-size:
11.0pt;font-family:Calibri'>run such copy</span><span style='font-size:11.0pt;
font-family:Calibri'> of the App </span><span style='font-size:11.0pt;
font-family:Calibri'>solely for your own personal non-commercial purposes. You
may not copy </span><span style='font-size:11.0pt;font-family:Calibri'>the App</span><span
            style='font-size:11.0pt;font-family:Calibri'>, except for making a </span><span
            style='font-size:11.0pt;font-family:Calibri'>reasonable number of copies for
backup or archival purposes.</span><span style='font-size:11.0pt;font-family:
Calibri'> Except as expressly permitted in these Terms, you may not: (i)&nbsp;copy,
modify or create derivative works based on</span><span style='font-size:11.0pt;
font-family:Calibri'> the App; (ii)&nbsp;distribute, transfer, sublicense,
lease, lend or rent the App to any third party; (iii)&nbsp;reverse engineer,
decompile or disassemble the App; or (iv)&nbsp;make the functionality of the
App available to multiple users through any means.&nbsp; SamsaSoftware reserves all
rights in and to the App not expressly granted to you under these Terms.</span></p>

    <p style='margin:0in;margin-bottom:.0001pt;text-align:justify'><span
            style='font-size:11.0pt;font-family:Calibri'>&nbsp;</span></p>

    <p class=MsoNormal style='margin-bottom:3.0pt;text-align:justify'><b><span
                style='font-family:Calibri'>General Prohibitions</span></b><b><span
                style='font-family:Calibri'> and SamsaSoftware's Enforcement Rights</span></b></p>

    <p class=MsoNormal style='margin-bottom:3.0pt;text-align:justify'><span
            style='font-size:11.0pt;font-family:Calibri'>You agree not to do any of the
following:</span></p>

    <p class=MsoNormal style='margin-left:27.4pt;text-align:justify;text-indent:
-13.7pt;background:white;punctuation-wrap:simple;text-autospace:none;
vertical-align:baseline'><span style='font-size:11.0pt;font-family:Symbol'>á<span
                style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span
            style='font-size:11.0pt;font-family:Calibri'>Use the Services in any way, or
post, upload, publish, submit or transmit any Content, that:
(i)&nbsp;infringes, misappropriates or violates a third party's patent,
copyright, trademark, trade secret, moral rights or other intellectual property
rights, or rights of publicity or privacy; (ii) violates, or encourages any
conduct that would violate, any applicable law or regulation or would give rise
to civil liability; (iii) is fraudulent, false, misleading or deceptive; (iv)
is defamatory, obscene, pornographic, vulgar or offensive; (v)&nbsp;promotes
discrimination, bigotry, racism, hatred, harassment or harm against any
individual or group; (vi) is violent or threatening or promotes violence or
actions that are threatening to any person or entity; or (vii)&nbsp;promotes
illegal or harmful activities or substances.</span></p>

    <p class=MsoNormal style='margin-left:27.4pt;text-align:justify;text-indent:
-13.7pt;background:white;punctuation-wrap:simple;text-autospace:none;
vertical-align:baseline'><span style='font-size:11.0pt;font-family:Symbol'>á<span
                style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span
            style='font-size:11.0pt;font-family:Calibri'>Use, display, mirror or frame the
Services or any individual element within the Services, SamsaSoftware's name, any SamsaSoftware
trademark, logo or other proprietary information, or the layout and design of
any page or form contained on a page, without SamsaSoftware's express written
consent;</span><span style='font-size:11.0pt;font-family:Calibri'> </span></p>

    <p class=MsoNormal style='margin-left:27.4pt;text-align:justify;text-indent:
-13.7pt;background:white;punctuation-wrap:simple;text-autospace:none;
vertical-align:baseline'><span style='font-size:11.0pt;font-family:Symbol'>á<span
                style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span
            style='font-size:11.0pt;font-family:Calibri'>Access, tamper with, or use
non-public areas of the Services, SamsaSoftware's computer systems, or the technical
delivery systems of SamsaSoftware's providers;</span><span style='font-size:11.0pt;
font-family:Calibri'> </span></p>

    <p class=MsoNormal style='margin-left:27.4pt;text-align:justify;text-indent:
-13.7pt;background:white;punctuation-wrap:simple;text-autospace:none;
vertical-align:baseline'><span style='font-size:11.0pt;font-family:Symbol'>á<span
                style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span
            style='font-size:11.0pt;font-family:Calibri'>Attempt to probe, scan or test the
vulnerability of any SamsaSoftware system or network or breach any security or
authentication measures;</span><span style='font-size:11.0pt;font-family:Calibri'>
</span></p>

    <p class=MsoNormal style='margin-left:27.4pt;text-align:justify;text-indent:
-13.7pt;background:white;punctuation-wrap:simple;text-autospace:none;
vertical-align:baseline'><span style='font-size:11.0pt;font-family:Symbol'>á<span
                style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span
            style='font-size:11.0pt;font-family:Calibri'>Avoid, bypass, remove, deactivate,
impair, descramble or otherwise circumvent any technological measure
implemented by SamsaSoftware or any of SamsaSoftware's providers or any other third
party (including another user) to protect the Services or Content;</span><span
            style='font-size:11.0pt;font-family:Calibri'> </span></p>

    <p class=MsoNormal style='margin-left:27.4pt;text-align:justify;text-indent:
-13.7pt;background:white;punctuation-wrap:simple;text-autospace:none;
vertical-align:baseline'><span style='font-size:11.0pt;font-family:Symbol'>á<span
                style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span
            style='font-size:11.0pt;font-family:Calibri'>Attempt to access or search the
Services or Content or download Content from the Services through the use of
any engine, software, tool, agent, device or mechanism (including spiders,
robots, crawlers, data mining tools or the like) other than the software and/or
search agents provided by SamsaSoftware or other generally available third-party
web browsers;</span><span style='font-size:11.0pt;font-family:Calibri'> </span></p>

    <p class=MsoNormal style='margin-left:27.4pt;text-align:justify;text-indent:
-13.7pt;background:white;punctuation-wrap:simple;text-autospace:none;
vertical-align:baseline'><span style='font-size:11.0pt;font-family:Symbol'>á<span
                style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span
            style='font-size:11.0pt;font-family:Calibri'>Send any unsolicited or
unauthorized advertising, promotional materials, email, junk mail, spam, chain
letters or other form of solicitation;</span><span style='font-size:11.0pt;
font-family:Calibri'> </span></p>

    <p class=MsoNormal style='margin-left:27.4pt;text-align:justify;text-indent:
-13.7pt;background:white;punctuation-wrap:simple;text-autospace:none;
vertical-align:baseline'><span style='font-size:11.0pt;font-family:Symbol'>á<span
                style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span
            style='font-size:11.0pt;font-family:Calibri'>Use any meta tags or other hidden
text or metadata utilizing a SamsaSoftware trademark, logo URL or product name
without SamsaSoftware's express written consent;</span><span style='font-size:11.0pt;
font-family:Calibri'> </span></p>

    <p class=MsoNormal style='margin-left:27.4pt;text-align:justify;text-indent:
-13.7pt;background:white;punctuation-wrap:simple;text-autospace:none;
vertical-align:baseline'><span style='font-size:11.0pt;font-family:Symbol'>á<span
                style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span
            style='font-size:11.0pt;font-family:Calibri'>Use the Services or Content, or
any portion thereof, for any commercial purpose or for the benefit of any third
party or in any manner not permitted by these Terms;</span><span
            style='font-size:11.0pt;font-family:Calibri'> </span></p>

    <p class=MsoNormal style='margin-left:27.4pt;text-align:justify;text-indent:
-13.7pt;background:white;punctuation-wrap:simple;text-autospace:none;
vertical-align:baseline'><span style='font-size:11.0pt;font-family:Symbol'>á<span
                style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span
            style='font-size:11.0pt;font-family:Calibri'>Forge any TCP/IP packet header or
any part of the header information in any email or newsgroup posting, or in any
way use the Services or Content to send altered, deceptive or false
source-identifying information;</span><span style='font-size:11.0pt;font-family:
Calibri'> </span></p>

    <p class=MsoNormal style='margin-left:27.4pt;text-align:justify;text-indent:
-13.7pt;background:white;punctuation-wrap:simple;text-autospace:none;
vertical-align:baseline'><span style='font-size:11.0pt;font-family:Symbol'>á<span
                style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span
            style='font-size:11.0pt;font-family:Calibri'>Attempt to decipher, decompile,
disassemble or reverse engineer any of the software used to provide the
Services or Content;</span><span style='font-size:11.0pt;font-family:Calibri'> </span></p>

    <p class=MsoNormal style='margin-left:27.4pt;text-align:justify;text-indent:
-13.7pt;background:white;punctuation-wrap:simple;text-autospace:none;
vertical-align:baseline'><span style='font-size:11.0pt;font-family:Symbol'>á<span
                style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span
            style='font-size:11.0pt;font-family:Calibri'>Interfere with, or attempt to
interfere with, the access of any user, host or network, including, without
limitation, sending a virus, overloading, flooding, spamming, or mail-bombing
the Services;</span><span style='font-size:11.0pt;font-family:Calibri'> </span></p>

    <p class=MsoNormal style='margin-left:27.4pt;text-align:justify;text-indent:
-13.7pt;background:white;punctuation-wrap:simple;text-autospace:none;
vertical-align:baseline'><span style='font-size:11.0pt;font-family:Symbol'>á<span
                style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span
            style='font-size:11.0pt;font-family:Calibri'>Collect or store any personally
identifiable information from the Services from other users of the Services
without their express permission;</span><span style='font-size:11.0pt;
font-family:Calibri'> </span></p>

    <p class=MsoNormal style='margin-left:27.4pt;text-align:justify;text-indent:
-13.7pt;background:white;punctuation-wrap:simple;text-autospace:none;
vertical-align:baseline'><span style='font-size:11.0pt;font-family:Symbol'>á<span
                style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span
            style='font-size:11.0pt;font-family:Calibri'>Impersonate or misrepresent your
affiliation with any person or entity; </span></p>

    <p class=MsoNormal style='margin-left:27.4pt;text-align:justify;text-indent:
-13.7pt;background:white;punctuation-wrap:simple;text-autospace:none;
vertical-align:baseline'><span style='font-size:11.0pt;font-family:Symbol'>á<span
                style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span
            style='font-size:11.0pt;font-family:Calibri'>Violate any applicable law or
regulation; or</span></p>

    <p class=MsoNormal style='margin-top:0in;margin-right:0in;margin-bottom:6.0pt;
margin-left:27.4pt;text-align:justify;text-indent:-13.7pt;background:white;
punctuation-wrap:simple;text-autospace:none;vertical-align:baseline'><span
            style='font-size:11.0pt;font-family:Symbol'>á<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><span style='font-size:11.0pt;font-family:Calibri'>Encourage or
enable any other individual to do any of the foregoing.</span></p>

    <h3 style='margin-bottom:0in;margin-bottom:.0001pt;text-align:justify;
text-indent:0in'><span lang=EN style='font-size:11.0pt;font-family:Calibri;
color:windowtext'>Although we're not obligated to monitor access to or use of
the Services or Content or to review or edit any Content, we have the right to
do so for the purpose of operating the Services, to ensure compliance with
these Terms, and to comply with applicable law or other legal requirements. We
reserve the right, but are not obligated, to remove or disable access to any Content,
at any time and without notice, including, but not limited to, if we, at our
sole discretion, consider any Content to be objectionable or in violation of
these Terms. We have the right to investigate violations of these Terms or
conduct that affects the Services. We may also consult and cooperate with law
enforcement authorities to prosecute users who violate the law.</span></h3>

    <p style='margin:0in;margin-bottom:.0001pt;text-align:justify'><span
            style='font-size:11.0pt;font-family:Calibri'>&nbsp;</span></p>

    <p class=MsoNormal style='text-align:justify'><b><span style='font-family:Calibri'>DMCA/Copyright
Policy</span></b></p>

    <p style='margin:0in;margin-bottom:.0001pt;text-align:justify'><span
            style='font-size:11.0pt;font-family:Calibri'>SamsaSoftware respects copyright law
and expects its users to do the same. It is SamsaSoftware's policy to terminate in
appropriate circumstances Account holders who repeatedly infringe or are
believed to be repeatedly infringing the rights of copyright holders. Please
see SamsaSoftware's Copyright and IP Policy at </span><a
            href="https://production.samsasoftware.com/terms/copyright"><span style='font-size:11.0pt;font-family:
Calibri'>https://production.samsasoftware.com/terms/copyright</span></a><span style='font-size:11.0pt;
font-family:Calibri'>, for further information.&nbsp; </span></p>

    <p class=MsoNormal style='text-align:justify'><span style='font-size:11.0pt;
font-family:Calibri'>&nbsp;</span></p>

    <p class=MsoNormal style='text-align:justify'><b><span style='font-family:Calibri'>Links
to Third Party Websites or Resources</span></b></p>

    <p style='margin:0in;margin-bottom:.0001pt;text-align:justify'><span
            style='font-size:11.0pt;font-family:Calibri'>The Services and App may contain links
to </span><span lang=EN style='font-size:11.0pt;font-family:Calibri'>third-party
websites or resources</span><span style='font-size:11.0pt;font-family:Calibri'>.
We provide these links only as a convenience and are not responsible for the
content, </span><span lang=EN style='font-size:11.0pt;font-family:Calibri'>products
or services on or available from those websites or resources </span><span
            style='font-size:11.0pt;font-family:Calibri'>or links displayed on such websites.
You acknowledge sole responsibility for and assume all risk arising from, your
use </span><span lang=EN style='font-size:11.0pt;font-family:Calibri'>of any
third-party websites or resources.</span></p>

    <p style='margin:0in;margin-bottom:.0001pt;text-align:justify'><span
            style='font-size:11.0pt;font-family:Calibri'>&nbsp;</span></p>

    <p class=MsoNormal style='text-align:justify'><b><span style='font-family:Calibri'>Termination</span></b></p>

    <p class=MsoNormal style='text-align:justify'><span style='font-size:11.0pt;
font-family:Calibri'>We may terminate your access to and use of the Services,
at our sole discretion, at any time and without notice to you. <span lang=EN>You
can stop using the Services at any time; you can also remove</span></span><span
            style='font-size:11.0pt;font-family:Calibri'> our App from your device</span><span
            style='font-size:11.0pt;font-family:Calibri'> at </span><span style='font-size:
11.0pt;font-family:Calibri'>any time.</span><span style='font-size:11.0pt;
font-family:Calibri'> </span><span lang=EN style='font-size:11.0pt;font-family:
Calibri;color:black'>Upon any termination, discontinuation or cancellation of
Services or your Account,</span><span lang=EN style='font-size:11.0pt;
font-family:Calibri;color:black'> </span><span lang=EN style='font-size:11.0pt;
font-family:Calibri;color:black'>all provisions of these Terms which by their
nature should survive will survive, including, </span><span lang=EN
                                                            style='font-size:11.0pt;font-family:Calibri;color:black'>without limitation, the
provisions entitled "Agreement to Terms," </span><span style='font-size:11.0pt;
font-family:Calibri'>"</span><span lang=EN style='font-size:11.0pt;font-family:
Calibri'>Feedback,"</span><span lang=EN style='font-size:11.0pt;font-family:
Calibri;color:black'> "</span><span style='font-size:11.0pt;font-family:Calibri'>Content</span><span
            style='font-size:11.0pt;font-family:Calibri'> and </span><span
            style='font-size:11.0pt;font-family:Calibri'>Content Rights,"</span><span
            style='font-size:11.0pt;font-family:Calibri;color:black'> <span lang=EN>"</span></span><span
            style='font-size:11.0pt;font-family:Calibri'>General Prohibitions</span><span
            style='font-size:11.0pt;font-family:Calibri'> and SamsaSoftware's Enforcement
Rights,"</span><span style='font-size:11.0pt;font-family:Calibri;color:black'> <span
                lang=EN>"</span></span><span style='font-size:11.0pt;font-family:Calibri'>Links
to Third Party Websites or Resources,"</span><span style='font-size:11.0pt;
font-family:Calibri;color:black'> <span lang=EN>"</span></span><span
            style='font-size:11.0pt;font-family:Calibri'>Termination,"<span
                style='color:black'> <span lang=EN>"</span></span><span>Warranty Disclaimers,"</span><span
                style='color:black'> <span lang=EN>"</span></span></span><span
            style='font-size:11.0pt;font-family:Calibri'>Indemnity,"</span><span
            style='font-size:11.0pt;font-family:Calibri;color:black'> <span lang=EN>"</span></span><span
            style='font-size:11.0pt;font-family:Calibri'>Limitation of Liability,"<span
                style='color:black'> <span lang=EN>"</span></span></span><span
            style='font-size:11.0pt;font-family:Calibri'>Dispute Resolution" and</span><span
            style='font-size:11.0pt;font-family:Calibri;color:black'> <span lang=EN>"</span></span><span
            style='font-size:11.0pt;font-family:Calibri'>General Terms." </span></p>

    <p class=MsoNormal style='text-align:justify'><span style='font-size:11.0pt;
font-family:Calibri'>&nbsp;</span></p>

    <p class=MsoNormal style='text-align:justify'><b><span style='font-family:Calibri'>Warranty
Disclaimers</span></b></p>

    <p class=MsoNormal style='text-align:justify'><span style='font-size:11.0pt;
font-family:Calibri;text-transform:uppercase'>The Services, Content AND ANY
DEVICE FURNISHED BY SamsaSoftware are provided "AS IS," without warranty of any
kind.</span><span style='font-size:11.0pt;font-family:Calibri'> <span
                style='text-transform:uppercase'>Without limiting the foregoing, </span>WE
EXPLICITLY DISCLAIM ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
PURPOSE, QUIET ENJOYMENT OR NON-INFRINGEMENT, <span>AND ANY WARRANTIES ARISING
OUT OF COURSE OF DEALING OR USAGE OF TRADE WITH RESPECT TO </span><span
                style='text-transform:uppercase'>The Services, Content AND DEVICES</span>. We
make no warranty that the Services will meet your requirements or be available
on an uninterrupted, secure, or error-free basis. We make no warranty regarding
the quality, accuracy, timeliness, truthfulness, completeness or reliability of
any Content</span><span lang=EN style='font-size:11.0pt;font-family:Calibri'>.&nbsp;
</span></p>

    <p class=MsoNormal style='text-align:justify'><span lang=EN style='font-size:
11.0pt;font-family:Calibri'>&nbsp;</span></p>

    <p class=MsoNormal style='text-align:justify'><span style='font-size:11.0pt;
font-family:Calibri'>SamsaSoftware</span><span style='font-size:11.0pt;font-family:
Calibri'> does not provide, inspect or control any </span><span
            style='font-size:11.0pt;font-family:Calibri'>child care and day care services</span><span
            style='font-size:11.0pt;font-family:Calibri'> and </span><span
            style='font-size:11.0pt;font-family:Calibri'>SamsaSoftware</span><span
            style='font-size:11.0pt;font-family:Calibri'> does not endorse, verify or vouch
for any </span><span style='font-size:11.0pt;font-family:Calibri'>C</span><span
            style='font-size:11.0pt;font-family:Calibri'>enters or their personnel</span><span
            style='font-size:11.0pt;font-family:Calibri'> </span><span style='font-size:
11.0pt;font-family:Calibri'>or other users of the Services.&nbsp; </span><span
            style='font-size:11.0pt;font-family:Calibri'>SamsaSoftware</span><span
            style='font-size:11.0pt;font-family:Calibri'>'s responsibilities under these
Terms are limited solely to facilitating the availability of the Services.&nbsp;
</span><span style='font-size:11.0pt;font-family:Calibri'>NEITHER SamsaSoftware NOR
ITS AFFILIATES OR LICENSORS ARE RESPONSIBLE FOR THE CONDUCT OF ANY DAY CARE OR
CHILD CARE CENTER, OR THEIR STAFF OR ANY OTHER USER OF THE SERVICES AND YOUR PROVISION
OR USE OF DAY CARE OR CHILD CARE SERVICES AND YOUR INTERACTIONS WITH PARENTS, DAY
CARE OR CHILD CARE CENTER, OR THEIR STAFF AND ANY OTHER USERS OF THE SERVICES ARE
ENTIRELY AT YOUR OWN RISK.&nbsp; YOU HEREBY RELEASE SamsaSoftware AND ITS
AFFILIATES AND LICENSORS FROM ANY LIABILITY RELATED TO ANY DAY CARE OR CHILD
CARE SERVICES YOU PROVIDE OR USE. &nbsp;SamsaSoftware AND ITS AFFILIATES AND
LICENSORS ARE NOT AND WILL NOT BE LIABLE FOR ANY CLAIM, PERSONAL INJURY OR PROPERTY
DAMAGE ARISING IN CONNECTION WITH YOUR PROVISION OR USE OF ANY DAY CARE OR
CHILD CARE SERVICES AND DISCLAIM ALL LIABILITY IN THIS REGARD.&nbsp; If you
have a dispute with any person or entity or any other user regarding day care
or child care services used or provided, your only resource is with each other
and you agree not to pursue any claim against SamsaSoftware in this regard.&nbsp; </span></p>

    <p class=MsoNormal style='text-align:justify'><b><span style='font-size:11.0pt;
font-family:Calibri'>&nbsp;</span></b></p>

    <p style='margin:0in;margin-bottom:.0001pt;text-align:justify'><b><span
                style='font-family:Calibri'>Indemnity</span></b></p>

    <p style='margin:0in;margin-bottom:.0001pt;text-align:justify'><span
            style='font-size:11.0pt;font-family:Calibri'>You will indemnify and hold harmless
SamsaSoftware and its officers, directors, employee and agents, from and against </span><span
            lang=EN style='font-size:11.0pt;font-family:Calibri'>any claims, disputes,
demands, liabilities, damages, losses, and costs and expenses, including,
without limitation, reasonable legal and accounting fees arising out of or in
any way connected with (i) your access to or use of the Services, Content or any
devices furnished by SamsaSoftware, (ii) your User Content, or (iii) your violation
of these Terms.</span></p>

    <p class=MsoNormal style='text-align:justify'><b><span style='font-size:11.0pt;
font-family:Calibri'>&nbsp;</span></b></p>

    <p class=MsoNormal style='text-align:justify'><b><span style='font-family:Calibri'>Limitation
of Liability</span></b></p>

    <p style='margin:0in;margin-bottom:.0001pt;text-align:justify'><span
            style='font-size:11.0pt;font-family:Calibri;text-transform:uppercase'>NEITHER SamsaSoftware
NOR ANY OTHER party involved in creating, producing, or delivering the services
or content </span><span style='font-size:11.0pt;font-family:Calibri;text-transform:
uppercase'>will be liable for any incidental, special, exemplary or
consequential damages,</span><span style='font-size:11.0pt;font-family:Calibri'>
INCLUDING LOST PROFITS, LOSS OF DATA OR GOODWILL, SERVICE INTERRUPTION,
COMPUTER DAMAGE OR SYSTEM FAILURE OR THE COST OF SUBSTITUTE SERVICES <span
                style='text-transform:uppercase'>arising ouT of or in connection with thESE
TERMS or from the use OF or inability to use the ServiceS or CONTENT or any
devices FURNISHED BY SamsaSoftware, whether based on warranty, contract, tort
(including negligence), PRODUCT LIABILITY or any other legal theory, and
whether or not SamsaSoftware has been informed of the possibility of such damage,</span></span><span
            style='font-size:11.0pt;font-family:Calibri;text-transform:uppercase'> EVEN IF
A limited REMEDY SET FORTH HEREIN IS FOUND TO HAVE FAILED OF ITS ESSENTIAL
PUrPOSE</span><span style='font-size:11.0pt;font-family:Calibri'>.<span> SOME
JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR
CONSEQUENTIAL OR INCIDENTAL DAMAGES, SO THE ABOVE LIMITATION MAY NOT APPLY TO
YOU.</span></span></p>

    <p style='margin:0in;margin-bottom:.0001pt;text-align:justify'><span
            style='font-size:11.0pt;font-family:Calibri'>&nbsp;</span></p>

    <p style='margin:0in;margin-bottom:.0001pt;text-align:justify'><span
            style='font-size:11.0pt;font-family:Calibri;text-transform:uppercase'>In no
event will SamsaSoftware'S total liability arising out of or in connection with</span><span
            style='font-size:11.0pt;font-family:Calibri'> THESE TERMS OR FROM THE USE OF OR
INABILITY TO USE </span><span style='font-size:11.0pt;font-family:Calibri;
text-transform:uppercase'>the ServiceS or content or any SamsaSoftware devices </span><span
            style='font-size:11.0pt;font-family:Calibri'>EXCEED $100.</span></p>

    <p style='margin:0in;margin-bottom:.0001pt;text-align:justify'><span
            style='font-size:11.0pt;font-family:Calibri'>&nbsp;</span></p>

    <p style='margin:0in;margin-bottom:.0001pt;text-align:justify'><span
            style='font-size:11.0pt;font-family:Calibri'>THE EXCLUSIONS AND LIMITATIONS OF
DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN
BETWEEN SamsaSoftware AND YOU.</span></p>

    <h1 style='margin-bottom:0in;margin-bottom:.0001pt;text-align:justify'><span
            style='font-size:11.0pt;font-family:Calibri'>&nbsp;</span></h1>

    <h1 style='margin-bottom:6.0pt;text-align:justify'><b><span style='font-family:
Calibri;color:windowtext'>Dispute Resolution</span></b></h1>

    <p class=MsoNormal style='text-align:justify'><u><span style='font-size:11.5pt;
font-family:Calibri'>Governing Law</span></u></p>

    <p class=MsoNormal style='text-align:justify'><span style='font-size:11.0pt;
font-family:Calibri'>These Terms and any action related thereto will be
governed by the laws of the State of California without regard to its conflict
of laws provisions.</span></p>

    <p class=MsoNormal style='text-align:justify'><u><span style='font-size:11.0pt;
font-family:Calibri'><span style='text-decoration:none'>&nbsp;</span></span></u></p>

    <p class=MsoNormal style='text-align:justify'><u><span style='font-size:11.5pt;
font-family:Calibri'>Agreement to Arbitrate</span></u></p>

    <p class=MsoNormal style='text-align:justify'><span style='font-size:11.0pt;
font-family:Calibri'>You and SamsaSoftware agree that<em><span style='font-family:
Calibri;color:#262626;font-style:normal'> any dispute, claim or controversy
arising out of or relating to these Terms or the breach, termination,
enforcement, interpretation or validity thereof or the use of the Services or Content
(collectively, "<b>Disputes</b>") will be settled by binding arbitration,
except that each party retains the right: (i) to bring an individual action in
small claims court and (ii) to seek </span></em>injunctive or other equitable
relief in a court of competent jurisdiction to prevent the actual or threatened
infringement, misappropriation or violation of a party's </span><span
            style='font-size:11.0pt;font-family:Calibri'>copyrights, trademarks, trade
secrets, patents or other </span><span style='font-size:11.0pt;font-family:
Calibri'>intellectual property rights (the action described in the foregoing
clause (ii), an "<b>IP Protection Action</b>"). The exclusive jurisdiction and
venue of any IP Protection Action will be the state and federal courts located
in the </span><span style='font-size:11.0pt;font-family:Calibri'>Northern
District of California and </span><span style='font-size:11.0pt;font-family:
Calibri'>each of </span><span style='font-size:11.0pt;font-family:Calibri'>the
parties </span><span style='font-size:11.0pt;font-family:Calibri'>hereto waives
any objection to jurisdiction and venue in such courts. <em><b><span
                        style='font-family:Calibri;color:#262626;font-style:normal'>You acknowledge and
agree that you and SamsaSoftware</span></b></em><b> are each waiving the right to a
                trial by jury or to participate as a plaintiff or class member in any purported
                class action or representative proceeding.</b> Further, unless both you and SamsaSoftware
otherwise agree in writing, the arbitrator may not consolidate more than one
person's claims, and may not otherwise preside over any form of any class or
representative proceeding. If this specific paragraph is held unenforceable,
then the entirety of this "Dispute Resolution" section will be deemed void.
Except as provided in the preceding sentence, this "Dispute Resolution" section
will survive any termination of these Terms.</span></p>

    <p class=MsoNormal style='text-align:justify'><em><span style='font-size:11.0pt;
font-family:Calibri;color:#262626;font-style:normal'>&nbsp;</span></em></p>

    <p class=MsoNormal style='text-align:justify'><em><u><span style='font-size:
11.5pt;font-family:Calibri;font-style:normal'>Arbitration Rules</span></u></em></p>

    <p class=MsoNormal style='text-align:justify'><em><span style='font-size:11.0pt;
font-family:Calibri;color:#262626;font-style:normal'>The arbitration will be
administered by </span></em><span style='font-size:11.0pt;font-family:Calibri'>the
American Arbitration Association ("<b>AAA</b>"</span><span style='font-size:
11.0pt;font-family:Calibri'>) </span><em><span style='font-size:11.0pt;
font-family:Calibri;color:#262626;font-style:normal'>in accordance with the </span></em><span
            style='font-size:11.0pt;font-family:Calibri'>Commercial Arbitration Rules and
the Supplementary Procedures for Consumer Related Disputes (the "<b>AAA Rules</b>")
then in effect, except as modified by this "Dispute Resolution" section. (The
AAA Rules are available at </span><a href="http://www.adr.org/arb_med"><span
                style='font-size:11.0pt;font-family:Calibri'>www.adr.org/arb_med</span></a><span
            style='font-size:11.0pt;font-family:Calibri'> or by calling the AAA at
1-800-778-7879.) The Federal Arbitration Act will govern the interpretation and
enforcement of this Section.</span></p>

    <p class=MsoNormal style='text-align:justify'><span style='font-size:11.0pt;
font-family:Calibri'>&nbsp;</span></p>

    <p class=MsoNormal style='text-align:justify'><u><span style='font-size:11.5pt;
font-family:Calibri'>Arbitration Process</span></u></p>

    <p class=MsoNormal style='text-align:justify'><span style='font-size:11.0pt;
font-family:Calibri'>A party who desires to initiate arbitration must provide
the other party with a written Demand for Arbitration as specified in the AAA
Rules. <span style='color:black'>(The AAA provides a form Demand for
Arbitration at </span></span><a
            href="http://www.adr.org/aaa/ShowPDF?doc=ADRSTG_015820"><span style='font-size:
11.0pt;font-family:Calibri'>http://www.adr.org/aaa/ShowPDF?doc=ADRSTG_015820</span></a><span
            style='font-size:11.0pt;font-family:Calibri;color:#1F497D'> </span><span
            style='font-size:11.0pt;font-family:Calibri;color:black'>and a separate form
for California residents at </span><span><span class=MsoHyperlink><span
                    style='font-size:11.0pt;font-family:Calibri'>http://www.adr.org/aaa/ShowPDF?doc=ADRSTG_015822</span></span></span><span
            style='font-size:11.0pt;font-family:Calibri;color:black'>.) </span><span
            style='font-size:11.0pt;font-family:Calibri'>The arbitrator will be either a
retired judge or an attorney licensed to practice law and will be selected by
the parties from the AAA's roster of arbitrators. If the parties are unable to
agree upon an arbitrator within seven (7) days of delivery of the Demand for
Arbitration, then the AAA will appoint the arbitrator in accordance with the
AAA Rules.</span></p>

    <p class=MsoNormal style='text-align:justify'><span style='font-size:11.0pt;
font-family:Calibri'>&nbsp;</span></p>

    <p class=MsoNormal style='text-align:justify'><u><span style='font-size:11.5pt;
font-family:Calibri'>Arbitration Location and Procedure</span></u></p>

    <p class=MsoNormal style='text-align:justify'><span style='font-size:11.0pt;
font-family:Calibri'>Unless you and SamsaSoftware otherwise agree, the arbitration
will be conducted in the county where you reside. If your claim does not exceed
$10,000, then the arbitration will be conducted solely on the basis of the
documents that you and SamsaSoftware submit to the arbitrator, unless you request a
hearing or the arbitrator determines that a hearing is necessary. If your claim
exceeds $10,000, your right to a hearing will be determined by the AAA Rules. Subject
to the AAA Rules, the arbitrator will have the discretion to direct a
reasonable exchange of information by the parties, consistent with the
expedited nature of the arbitration.</span></p>

    <p class=MsoNormal style='text-align:justify'><span style='font-size:11.0pt;
font-family:Calibri'>&nbsp;</span></p>

    <p class=MsoNormal style='text-align:justify'><u><span style='font-size:11.0pt;
font-family:Calibri'>Arbitrator's Decision</span></u></p>

    <p class=MsoNormal style='text-align:justify'><span style='font-size:11.0pt;
font-family:Calibri'>The arbitrator will render an award within the time frame
specified in the AAA Rules. <span style='color:black'>The arbitrator's decision
will include the essential findings and conclusions upon which the arbitrator
based the award. </span></span><span class=s7078511><span style='font-size:
11.0pt;font-family:Calibri'>J</span></span><span style='font-size:11.0pt;
font-family:Calibri'>udgment on the arbitration award may be entered in any
court having jurisdiction thereof. <span>The arbitrator's award of damages must
be consistent with the terms of the "Limitation of Liability" section above as
to the types and amounts of damages for which a party may be held liable. </span>The
arbitrator may award declaratory or injunctive relief only in favor of the
claimant and only to the extent necessary to provide relief warranted by the
claimant's individual claim. </span><span class=s7078511><span
                style='font-size:11.0pt;font-family:Calibri'>If you prevail in arbitration you
will be entitled to an award of attorneys' fees and expenses, to the extent
provided under applicable law. </span></span><span style='font-size:11.0pt;
font-family:Calibri'>SamsaSoftware will not seek, and </span><span
            style='font-size:11.0pt;font-family:Calibri'>hereby </span><span
            style='font-size:11.0pt;font-family:Calibri'>waives all rights it may have
under applicable law to recover, attorneys' fees and expenses if it prevails in
arbitration.</span></p>

    <p class=MsoNormal style='text-align:justify'><u><span style='font-size:11.0pt;
font-family:Calibri'><span style='text-decoration:none'>&nbsp;</span></span></u></p>

    <p class=MsoNormal style='text-align:justify'><u><span style='font-size:11.5pt;
font-family:Calibri'>Fees</span></u></p>

    <p class=MsoNormal style='text-align:justify'><span style='font-size:11.0pt;
font-family:Calibri'>Your responsibility to pay any AAA filing, administrative
and arbitrator fees will be solely as set forth in the AAA Rules. However, if
your claim for damages does not exceed $75,000, SamsaSoftware will pay all such
fees unless the arbitrator finds that either the substance of your claim or the
relief sought in your Demand for Arbitration was frivolous or was brought for
an improper purpose (as measured by the standards set forth in Federal Rule of
Civil Procedure 11(b)).</span></p>

    <p class=MsoNormal style='text-align:justify'><span style='font-size:11.0pt;
font-family:Calibri'>&nbsp;</span></p>

    <p style='margin:0in;margin-bottom:.0001pt;text-align:justify'><u><span
                style='font-size:11.5pt;font-family:Calibri'>Changes</span></u></p>

    <p style='margin:0in;margin-bottom:.0001pt;text-align:justify'><span
            style='font-size:11.0pt;font-family:Calibri'>Notwithstanding the provisions of
the "</span><span style='font-size:11.0pt;font-family:Calibri'>Changes to Terms
or Services</span><span style='font-size:11.0pt;font-family:Calibri'>" section
above, if SamsaSoftware changes this "Dispute Resolution" section after the date you
first accepted these Terms (or accepted any subsequent changes to these Terms),
you may reject any such change by sending us written notice (including by email
to </span><a href="mailto:info@samsasoftware.nl"><span style='font-size:11.0pt;
font-family:Calibri'>info@samsasoftware.nl</span></a><span style='font-size:11.0pt;
font-family:Calibri'>) within 30 days of the date such change became effective,
as indicated in the "Last Updated" date above or in the date of SamsaSoftware's
email to you notifying you of such change. By rejecting any change, you are
agreeing that you will arbitrate any Dispute between you and SamsaSoftware in accordance
with the provisions of this "Dispute Resolution" section as of the date you
first accepted these Terms (or accepted any subsequent changes to these Terms).</span></p>

    <p style='margin:0in;margin-bottom:.0001pt;text-align:justify'><span
            style='font-size:11.0pt;font-family:Calibri'>&nbsp;</span></p>

    <p class=MsoNormal style='text-align:justify'><b><span style='font-family:Calibri'>General
Terms</span></b></p>

    <p class=MsoNormal style='text-align:justify'><span style='font-size:11.0pt;
font-family:Calibri'>These Terms constitute the entire and exclusive
understanding and agreement between SamsaSoftware and you regarding the Services and
Content, and these Terms supersede and replace any and all prior oral or
written understandings or agreements between SamsaSoftware and you regarding the
Services and Content. </span><span style='font-size:11.0pt;font-family:Calibri'>If
for any reason a court of competent jurisdiction finds any provision of these
Terms invalid or unenforceable, that provision will be enforced to the maximum
extent permissible and the other provisions of these Terms will remain in full
force and effect.</span></p>

    <p class=MsoNormal style='text-align:justify'><span style='font-size:11.0pt;
font-family:Calibri'>&nbsp;</span></p>

    <p class=MsoNormal style='text-align:justify'><span style='font-size:11.0pt;
font-family:Calibri'>You may not assign or transfer these Terms, by operation
of law or otherwise, without SamsaSoftware's prior written consent. Any attempt by
you to assign or transfer these Terms, without such consent, will be null. SamsaSoftware
may freely assign or transfer these Terms without restriction. Subject to the
foregoing, these Terms will bind and inure to the benefit of the parties, their
successors and permitted assigns.</span></p>

    <p class=MsoBodyText style='margin-bottom:0in;margin-bottom:.0001pt;text-indent:
0in'><span style='font-size:11.0pt;font-family:Calibri'>&nbsp;</span></p>

    <p class=MsoNormal style='text-align:justify'><span style='font-size:11.0pt;
font-family:Calibri'>Any notices or other communications provided by SamsaSoftware
under these Terms, including those regarding modifications to these Terms, will
be given: (i) via email</span> <span style='font-size:11.0pt;font-family:Calibri'>to
the email address you provide us via the Services; or (ii) by posting to the
Services. For notices made by e-mail, the date of receipt will be deemed the
date on which such notice is transmitted.</span></p>

    <p style='margin:0in;margin-bottom:.0001pt;text-align:justify'><span
            style='font-size:11.0pt;font-family:Calibri'>&nbsp;</span></p>

    <h3 style='margin-bottom:0in;margin-bottom:.0001pt;text-align:justify;
text-indent:0in'><span style='font-size:11.0pt;font-family:Calibri'>SamsaSoftware's
failure to enforce any right or provision of these Terms will not be considered
a waiver of such right or provision. The waiver of any such right or provision
will be effective only if in writing and signed by a duly authorized
representative of SamsaSoftware. Except as expressly set forth in these Terms, the
exercise by either party of any of its remedies under these Terms will be
without prejudice to its other remedies under these Terms or otherwise.</span></h3>

    <p class=MsoNormal style='text-align:justify'><b><span style='font-size:11.0pt;
font-family:Calibri'>&nbsp;</span></b></p>

    <p class=MsoNormal style='text-align:justify'><b><span style='font-family:Calibri'>Contact
Information</span></b></p>

    <p class=MsoBodyText style='margin-bottom:0in;margin-bottom:.0001pt;text-align:
justify;text-indent:0in'><span style='font-size:11.0pt;font-family:Calibri'>If
you have any questions about these Terms or the Services,</span><span
            style='font-size:11.0pt;font-family:Calibri'> </span><span style='font-size:
11.0pt;font-family:Calibri'>please contact SamsaSoftware at </span><a
            href="mailto:info@samsasoftware.nl"><span style='font-size:11.0pt;font-family:Calibri'>info@samsasoftware.nl</span></a><i><span
                style='font-size:11.0pt;font-family:Calibri'>.</span></i></p>

</div>

</body>

</html>
