<?php
$this->flashMessages($flashMessages);
?>
<script>
    $(document).ready(function(){
        "use strict";
        $('.register-form').validate({
            invalidHandler: function (event, validator) {
                // Your invalid handler goes here
            }
        });
    });
</script>
<div class="logo" xmlns="http://www.w3.org/1999/html">
    <strong>Samsa</strong> Software
</div>
<div class="box">
    <div class="content">
        <h3 class="form-title"><?php echo $this->translate('signup_create_user');?> into <strong><?php echo $this->organization->getName();?></strong></h3>

        <form method="POST" class="register-form" name="register-form" action="<?php echo $this->url('auth', array('action' => 'createUser'));?>">
            <div class="form-group">
                <div class="input-icon">
                    <i class="icon-user"></i>
                    <input type="text" name="name" class="form-control" placeholder="First Name" autofocus="autofocus" data-rule-required="true" data-msg-required="Please enter your first name." />
                </div>
            </div>
            <div class="form-group">
                <div class="input-icon">
                    <i class="icon-user"></i>
                    <input type="text" name="lastname" class="form-control" placeholder="Last Name" autofocus="autofocus" data-rule-required="true" data-msg-required="Please enter your last name." />
                </div>
            </div>
            <div class="form-group">
                <div class="input-icon">
                    <i class="icon-envelope"></i>
                    <input type="text" name="email" class="form-control" placeholder="Email address" autofocus="autofocus" data-rule-required="true" data-msg-required="Please enter your email." />
                </div>
                <input type="hidden" id="organization" class="form-control" name="organization" value="<?php echo $this->organization->getDbName(); ?>">
            </div>
            <div class="form-actions">
                <input type="submit" class="submit btn btn-primary pull-right" value="<?php echo $this->translate('send_label');?>"/>
            </div>
        </form>
    </div>
</div>