<?php echo $this->doctype(); ?>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<html lang="en">
<head>
    <meta charset="utf-8">
    <?php $organization = $this->sessionHelper()->getOrganization(); ?>
    <?php if (getenv('APP_ENV') == 'production') {
        $favicon = 'favicon';
        if ($organization != null) {
            echo $this->headTitle($organization->getName())->setSeparator(' - ')->setAutoEscape(false);
        } else {
            echo $this->headTitle($this->translate('app_name'))->setSeparator(' - ')->setAutoEscape(false);
        }
    } else {
        if ($organization != null) {
            echo $this->headTitle('[' . getenv('APP_ENV') . ']' . $organization->getName())->setSeparator(' - ')->setAutoEscape(false);
        } else {
            echo $this->headTitle('[' . getenv('APP_ENV') . ']' . $this->translate('app_name'))->setSeparator(' - ')->setAutoEscape(false);

        }
    }
    ?>
    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/'.$favicon.'.ico'))
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))

        ->prependStylesheet($this->basePath('css/chat.css'))
    ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('js/common.js'))
        ->prependFile($this->basePath('js/jquery.validate.min.js'))
        ->prependFile($this->basePath('js/bootstrap.min.js'))

        ->prependFile($this->basePath('js/chat/handlebars.min.js'))
        ->prependFile($this->basePath('js/chat/main.js'))
        ->prependFile($this->basePath('js/chat/moment.min.js'))
        ->prependFile($this->basePath('js/chat/websocket.js'))
        ->prependFile($this->basePath('js/chat/swf_object.js'))
        ->prependFile($this->basePath('js/jquery.min.js'))
    ; ?>


</head>

<body>

<?php
$user = $this->permission()->getUser();
if ($user === null) {
    $role = 'anonymous';
} else {
    $role = $user->getUserRole()->getRole();
}
$acl = $this->permission()->getAcl();
//$session = $this->sessionHelper()->getSession()
?>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" id="navbar" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('home', array('action' => 'view')) ?>">
                <?php $organization = $this->sessionHelper()->getOrganization();
                if ($organization != null) { ?>
                    <img id="logo" src="<?php echo $this->basePath($organization->getLogo());?>">
                <?php } else {?>
                    <img id="logo" src="<?php echo $this->basePath('img/rsz_1.png');?>">
                <?php } ?>

            </a>
        </div>
        <div class="navbar-collapse collapse ">
            <?php
            echo $this->navigation('Navigation')
                ->setAcl($acl)
                ->setRole($role)
                ->menu()
                ->setPartial('partial/submenu')
                ->render();
            ?>
            <?php if ($user != null) { ?>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="javascript:void(0)"><?php echo $user->getName().' '.$user->getLastName(); ?></a></li>
                    <li><a href="<?php echo $this->url('user', array('action' => 'profile'));?>"><?php echo $this->translate('profile_label') ?></a></li>
                    <li><a href="<?php echo $this->url('auth', array('action' => 'logout'));?>"><?php echo $this->translate('menu_logout') ?></a></li>
                </ul>
            <?php }?>
        </div><!--/.nav-collapse -->
    </div>
</nav>
<div class="container">
    <?php echo $this->content; ?>
</div> <!-- /container -->


</body>
<script type = "text/javascript" >
    history.pushState(null, null, 'pagename');
    window.addEventListener('popstate', function(event) {
        history.pushState(null, null, 'pagename');
    });
</script>

</html>
