<script>
    $(document).ready(function(){
        "use strict";
        $('#addorganization').validate();
    });
</script>
<?php
$this->flashMessages($flashMessages);

$this->form->setAttribute('action', $this->url('organization', array('action' => 'save')));
$this->form->setAttribute('class', 'form-horizontal row-border');
$this->form->setAttribute('id', 'addorganization');
$this->form->setAttribute('autocomplete', 'off');
$this->form->prepare(); ?>

<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <div class="widget box">
            <div class="widget-header">
                <h4><i class="icon-reorder"></i> Add organization</h4>
                <div class="toolbar no-padding">

                </div>
            </div>
            <div class="widget-content">
                <?php
                echo $this->form()->openTag($this->form);
                ?>
                <?php
                echo $this->formInput($this->form->get('id'));
                ?>
                <div class="form-group">
                    <label class="col-md-2 control-label" for="name"><?php echo $this->formLabel($this->form->get('name')); ?></label>
                    <?php
                    echo $this->formInput($this->form->get('name'));
                    ?>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label" for="name"><?php echo $this->formLabel($this->form->get('email')); ?></label>
                    <?php
                    echo $this->formInput($this->form->get('email'));
                    ?>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label" for="name"><?php echo $this->formLabel($this->form->get('classpath')); ?></label>
                    <div class="col-md-10">
                        <div class="row">
                            <div class="col-md-4">
                                <?php
                                echo $this->formSelect($this->form->get('classpath'));
                                ?>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-2 control-label" for="locale"><?php echo $this->formLabel($this->form->get('locale')); ?></label>
                    <div class="col-md-10">
                        <div class="row">
                            <div class="col-md-4">
                                <?php
                                echo $this->formSelect($this->form->get('locale'));
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label" for="description"><?php echo $this->formLabel($this->form->get('description')); ?></label>
                    <?php
                    echo $this->formTextarea($this->form->get('description'));
                    ?>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label" for="deleted"><?php echo $this->formLabel($this->form->get('deleted')); ?></label>
                    <div class="col-md-10">
                        <div class="row">
                            <div class="col-md-4">
                                <?php
                                echo $this->formSelect($this->form->get('deleted'));
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label" for="name"><?php echo $this->formLabel($this->form->get('logo')); ?></label>
                    <?php
                    echo $this->formInput($this->form->get('logo'));
                    ?>
                </div>
                <div class="form-group">
                    <?php if ($this->organization != null) {?>
                        <img src="<?php echo $this->basePath($this->organization->getLogo());?>">
                    <?php } ?>
                </div>
                <?php
                echo $this->formInput($this->form->get('id'));
                ?>
                <div class="form-actions">
                    <?php echo $this->formRow($this->form->get('submit')); ?>
                </div>


                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
