
<?php
$this->flashMessages($flashMessages);
?>
<div class="row">
    <div class="col-md-12">
        <div class="widget box">
            <div class="widget-header">
                <h4><i class="icon-reorder"></i> <?php echo $this->translate('user_list_label');?></h4>
                <div class="toolbar no-padding">

                </div>
            </div>
            <div class="widget-content">
                <p>
                    <a href="<?php echo $this->url('user', array('action' => 'add'));?>" class="btn btn-success"><?php echo $this->translate('add_label'); ?></a>

                </p>
                <table class="table table-striped table-bordered table-hover table-checkable datatable">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th><?php echo $this->translate('email_label'); ?></th>
                        <th><?php echo $this->translate('name_label'); ?></th>
                        <th><?php echo $this->translate('role_label'); ?></th>
                        <th><?php echo $this->translate('status_label'); ?></th>
                        <th><?php echo $this->translate('options_label'); ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->users as $key => $user) { ?>
                        <tr>
                            <td><?php echo $key; ?></td>
                            <td><?php echo $user->getEmail(); ?></td>
                            <td><?php echo $user->getName(); ?></td>
                            <td><?php echo $user->getUserRole()->getRole(); ?></td>
                            <td>
                                <?php if($user->getDeleted() == 0) { ?>
                                    <button type="button" class="btn btn-success" disabled="disabled"><?php echo $this->translate('active_status'); ?></button>
                                <?php } else {?>
                                    <button type="button" class="btn btn-danger" disabled="disabled"><?php echo $this->translate('disable_status'); ?></button>
                                <?php } ?>
                            </td>
                            <td>
                                <a href="<?php echo $this->url('user', array('action' => 'add', 'id' => $user->getId()));?>" type="button" class="btn btn-info"><?php echo $this->translate('edit_label'); ?></a>
                                <a href="<?php echo $this->url('user', array('action' => 'delete', 'id' => $user->getId()));?>" type="button" class="btn btn-warning"><?php echo $this->translate('change_status_label'); ?></a>
                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
