<?php
$this->flashMessages($flashMessages);
?>

<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <div class="widget box">
            <div class="widget-header">
                <h4><i class="icon-reorder"></i>Change Password</h4>
                <div class="toolbar no-padding">

                </div>
            </div>
            <div class="widget-content">
            <form method="POST" autocomplete="off" id="change-password" name="change-password" action="<?php echo $this->url('user', array('action' => 'savepassword'));?>">
                <div class="form-group">
                    <label class="col-md-2 control-label" for="name"><?php echo $this->translate('current_password'); ?></label>
                    <input type="password" name="current_password" class="form-control input-width-xlarge required">
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label" for="name"><?php echo $this->translate('new_password'); ?></label>
                    <input type="password" id="new_password" name="new_password" class="form-control input-width-xlarge required">
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label" for="name"><?php echo $this->translate('re_new_password'); ?></label>
                    <input type="password" id="re_new_password" name="re_new_password" class="form-control input-width-xlarge required">
                </div>
                <div class="form-actions">
                    <input type="submit" value="<?php echo $this->translate('submit_label'); ?>" class="btn btn-default" id="submit" name="submit">
                </div>
            </form>
            </div>
        </div>
    </div>
</div>
