<?php
$this->flashMessages($flashMessages);
?>

<div class="row">

    <div class="col-md-4">
        <form method="POST" action="<?php echo $this->url('user', array('action' => 'changePasswordAfterReset'));?>">
            <div class="form-group">
                <label for="name"><?php echo $this->translate('new_password'); ?></label>
                <input type="password" id="new_password" name="new_password">
            </div>
            <div class="form-group">
                <label for="name"><?php echo $this->translate('re_new_password'); ?></label>
                <input type="password" id="re_new_password" name="re_new_password">
            </div>
            <input type="hidden" name="userId" value="<?php echo $this->userId; ?>"/>
            <div class="form-group">
                <input type="submit" value="<?php echo $this->translate('send_label');?>"/>
            </div>
        </form>
    </div>

</div>