<?php
namespace Application\Document\Simulator;

use Application\Document\Model;
use Application\Document\Indexer;
use Application\Document\UserTemplate;

class Profileattribute extends Model
{

    //    public $sfriends = array();
    //    public $susers = array();
        public $name;
    public $value;
    public $prottectedattribute = false;


    public static function getRelationType($name)
    {
                $relations = array();
        //        $relations['susers'] = Model::ONE_TO_MANY;
                return self::getRelationFromArray($name, $relations);
    }

    public function getRelationDetails($name)
    {
                $simplerelations = array();

                return parent::getRelationRefFromArray($name, $simplerelations); // TODO: Change the autogenerated stub
    }

    public function openPV(){
                //return strng
            }

    public function getTooltip($templateId = null, $idArray = null)
    {
                if ($templateId == "name")
                    {
                        return "The name for your personal data";
        }

    }

    public function remove($object, $softRemove = true, $noPropagation = false)
    {
        if($object instanceof Profile){
            if($object->prottectedattribute == true){
                return 'Protected attribute can\'t be deleted';
            }
        }

        parent::remove($object, $softRemove, $noPropagation);
    }
}