<?php
namespace Application\Document\Simulator;

use Application\Document\Model;
use Application\Document\Indexer;
use Application\Document\UserTemplate;

class Sconfig extends Model
{

    public $name;

    public static function getRelationType($name)
    {
        $relations = array();
        return self::getRelationTypeArray($name, $relations);
    }

    public function getRelationDetails($name)
    {
        $simplerelations = array();
        
        return parent::getRelationRefFromArray($name, $simplerelations); // TODO: Change the autogenerated stub
    }

    public function openPV(){
        //return strng
    }
}