<?php
namespace Application\Document\Simulator;

use Application\Document\Model;
use Application\Document\Indexer;
use Application\Document\UserTemplate;

class Stype extends Model
{

    public $sfriends = array();
    public $susers = array();
    public $name;

    public static function getPK() {
        return 'name';
    }

    public static function getRelationType($name)
    {
        $relations = array();
        $relations['susers'] = Model::ONE_TO_MANY;
        return self::getRelationFromArray($name, $relations);
    }

    public function getRelationDetails($name)
    {
        $simplerelations = array();
        
        return parent::getRelationRefFromArray($name, $simplerelations); // TODO: Change the autogenerated stub
    }

    public function openPV(){
        //return strng
    }
}