<script>
    var selectedItems = [];
    var oldSelection = 0;
    var selectedRefItems = [];
    var selectedRef2Items = [];
    var grids = [];
    // widget configuration
    var config = {
        layout: {
       	 name: 'layout<?php echo $this->viewId;?>',
         padding: 4,
         panels: [
             { type: 'top', size: '30%', resizable: true },
             { type: 'left', size: '50%', resizable: true},
             { type: 'main',  size: '50%',resizable: true },
             { type: 'preview',size: '50%',resizable: true },
             //{ type: 'right', size: '50%' ,resizable: true }
         ]
        },
       
        gridMenu: { 
        	name: 'gridMenu<?php echo $this->viewId;?>',
        	show: {
                toolbar            : true,
                header : true,               
            },
            multiSearch : true,
            searches: [{ field: 'recid', caption: 'ID ', type: 'int' }],
            reorderColumns: true,
            menu: [],
            records: [],
            onClick: function(event) {
                var grid = this;
                event.onComplete = function () {
                    var sel = grid.getSelection();
                    $.ajax({
                        type : 'POST',
                        url: $('#urlAjax').val()+"/getMethodResult?objectType="+"<?php echo $this->parentType; ?>"+"&methodName=get"+"<?php echo $this->id; ?>"+"&id="+event.recid,
                        
                         success:$.proxy(function(result){
                             w2ui['grid<?php echo $this->viewId;?>'].records = result.records;
                             w2ui['grid<?php echo $this->viewId;?>'].columns = result.columns;
                             w2ui['grid<?php echo $this->viewId;?>'].searches = result.search;                               
                           	 w2ui['grid<?php echo $this->viewId;?>'].reload();
                             w2ui['grid<?php echo $this->viewId;?>'].parentType = '<?php echo $this->parentType; ?>';
                             w2ui['grid<?php echo $this->viewId;?>'].parentId =event.recid;
                          }, this),
                         dataType : 'json'
                      });
                  
                  }
                }
            },         
        grid: {
            name: 'grid<?php echo $this->viewId;?>',
          
            show: {
                toolbar            : true,                
                header : true,
                selectColumn: true,
                footer    : true
            },
            multiSearch : true,
            searches: [{ field: 'recid', caption: 'ID ', type: 'int' }],
            reorderColumns: true,
            toolbar: {
                items: [
                    {
                        type :  'menu', id:'menu', caption:  '<?php echo $this->translate('Menu'); ?>', icon: 'fa-table', items:[
                            {
                                id: 'add',
                                type: 'button',
                                caption: '<?php echo $this->translate('common_add_record'); ?>',
                                icon: 'w2ui-icon-plus'
                            },
                            {
                                id: 'delete',
                                type: 'button',
                                caption: '<?php echo $this->translate('common_delete_record'); ?>',
                                icon: 'w2ui-icon-plus'
                            },
                            {
                                id: 'add-field',
                                type: 'button',
                                caption: '<?php echo $this->translate('common_add_field'); ?>',
                                icon: 'w2ui-icon-plus'
                            },
                            {   id: 'print',
                                type: 'button',
                                caption: '<?php echo $this->translate('export_field'); ?>',
                                icon: 'w2ui-icon-info'
                            }
                        ]
                    }
                ],
                onClick: function (event) {

                    if (event.target == 'menu:add') {
                        //w2ui.grid.add({ recid: '' });
                    	openAddPopup('<?php echo $this->id; ?>','<?php echo $this->parentType; ?>','<?php echo $this->parentId; ?>', 'grid','<?php echo $this->parentId; ?>','<?php echo $this->parentType; ?>',"new");
                    
                    }
                    if (event.target == 'menu:delete') {
                    	w2confirm('<?php echo $this->translate('are_you_sure'); ?>', function btn(answer) { 
                        	if(answer=='Yes')
                            { // Yes or No -- case-sensative

                            $.ajax({
                                type : 'POST',
                                url: $('#urlAjax').val()+"/deleteobjects",
                                data :  {
                                   	"parentId" : "<?php echo $this->parentId; ?>",
                                	"parentType" : ""+"<?php echo $this->parentType; ?>",
                                    "objectType" : "<?php echo $this->id; ?>",
                                    "data" : w2ui['grid<?php echo $this->viewId;?>'].getSelection()
                                },
                                success:$.proxy(function(result){
                                    if(result.success) {
                                        
                                        selectedItems = [];
                                        //refresh the page after delete the field
                                        simpleReloadGridData('grid','<?php echo $this->parentType; ?>', '<?php echo $this->parentId; ?>','<?php echo $this->id; ?>', true);
                                        //window.location = window.location;
                                        //refresh the page after delete the field
                                        simpleReloadGridData('gridRef',w2ui['gridRef<?php echo $this->viewId;?>'].parentType, w2ui['gridRef<?php echo $this->viewId;?>'].parentId,w2ui['gridRef<?php echo $this->viewId;?>'].objectTypeRef, true);
                                        //window.location = window.location;
                                        simpleReloadGridData('gridRef2',w2ui['gridRef2<?php echo $this->viewId;?>'].parentType, w2ui['gridRef2<?php echo $this->viewId;?>'].parentId,w2ui['gridRef2<?php echo $this->viewId;?>'].objectTypeRef, true);
                                        //window.location = window.location;
                                        simpleReloadGridData('gridRef3',w2ui['gridRef3<?php echo $this->viewId;?>'].parentType, w2ui['gridRef3<?php echo $this->viewId;?>'].parentId,w2ui['gridRef3<?php echo $this->viewId;?>'].objectTypeRef, true);
                                        
                                     }
                                }, this),
                                dataType : 'json'
                            });
                            }
                    	});
                                        
                    }
                    if (event.target == 'menu:add-field') {
                        
                        openPopup('<?php echo $this->id;?>');
                    }
                    if (event.target == 'menu:print') {
                    	var searchString= JSON.stringify(w2ui['grid<?php echo $this->viewId;?>'].searchData);
                   	    var searchField= JSON.stringify(w2ui['grid<?php echo $this->viewId;?>'].searchField);                  	  
                   	    var sortData= JSON.stringify(w2ui['grid<?php echo $this->viewId;?>'].sortData);
                        window.location = $('#urlAjax').val()+
                        "/export?object=get"+"<?php echo $this->id; ?>"+
                        "&viewId="+"<?php echo $this->viewId?>"+
                        "&gridId="+"grid"+ 
                        "&parentObject="+'<?php echo $this->parentType; ?>'+
                        "&parentId="+'<?php echo $this->parentId; ?>'+
                        "&searchData="+searchString+
                        "&searchField="+searchField+
                        "&sortData="+sortData;
                    }
                }
            },
            menu: [],
            records: [],
            onSearch : function (event) {               
                event.onComplete = function () {
                   console.log(event);
                   w2ui['grid<?php echo $this->viewId;?>'].searchData =event.searchData ;
                   w2ui['grid<?php echo $this->viewId;?>'].searchField =event.searchField ;
                   w2ui['gridRef<?php echo $this->viewId;?>'].clear() ;
                   w2ui['gridRef2<?php echo $this->viewId;?>'].clear() ;
                   w2ui['gridRef3<?php echo $this->viewId;?>'].clear() ;
                }
            },
            onMenuClick: function(event) {
            	if (event.menuItem.id == 1) {
                	openAddPopup('<?php echo $this->id; ?>','<?php echo $this->parentType; ?>','<?php echo $this->parentId; ?>', 'grid',event.recid,'<?php echo $this->id; ?>', 'edit');               
                	     
                }  else if (event.menuItem.id != '') {
                    if( event.menuItem.action == "popup"){
                        //
                    	console.log('start popup'+event.menuItem.viewId+" -- "+parentId);
                        //popup(""+event.menuItem.viewId, ""+event.menuItem.parentType, ""+event.menuItem.objectType,""+event.menuItem.method,""+parentId);    
                        popup(""+event.menuItem.viewId, '<?php echo $this->id; ?>', event.recid, ""+event.menuItem.parentType,""+event.menuItem.objectType,""+event.menuItem.method);     
                                                  
                    } else if( event.menuItem.actionExecution == "inputform"){
                        var objectTypeRef = w2ui['grid<?php echo $this->viewId;?>'].objectTypeRef;
                        openAddPopup(event.menuItem.method, '<?php echo $this->id; ?>',event.recid, 'gridRef', event.recid,'<?php echo $this->id; ?>', 'inputForm');
                    }
                    else if( event.menuItem.actionExecution == "service" || event.menuItem.actionExecution == "method"){
                    	console.log(event);
                    	event.menuItem.workspaceId= "<?php echo $this->sessionHelper()->getWorkspaceId();?>";
                        executeMenuAction(event, event.recid, '<?php echo $this->parentId; ?>');

                    }else if (event.menuItem.id != '') {
                 	   var objectTypeRef = w2ui.grid.objectTypeRef;
                	    //console.log("menu load= "+event );
                	    w2ui['layoutMain'].load(
                	    	    'main',
                	    	      $('#urlAjax').val()+"/view/"+result.items[0].link+
                	    	      "?layout=layoutMain&parentType="+"<?php echo $this->parentType;?>"+
                	    	      "\\"+objectTypeRef+"&parentId="+"<?php echo $this->id;?>"+
                	    	      "&viewId="+event.menuItem.id+"&objectId="+event.recid
                	    	      );
                	    }
                }
            },         
            onClick : function (event){
          //      w2ui['gridRef<?php echo $this->viewId;?>'].lock('Loading...', true); 
           	 event.onComplete = function () {
        		//w2ui['gridRef<?php echo $this->viewId;?>'].lock('Loading...', true); 
            	var sel = w2ui['grid<?php echo $this->viewId;?>'].getSelection();
            	if(sel.length == 1){             	
                   	   
               	    var sel = w2ui['grid<?php echo $this->viewId;?>'].getSelection();
               	    if( sel == oldSelection ) {}
                   	else{
             	          simpleReloadGridData('gridRef', "<?php echo $this->id; ?>",  sel,w2ui['gridRef<?php echo $this->viewId;?>'].objectTypeRef ); 
                      	  
                	      cleanGrid('gridRef2');
                	      cleanGrid('gridRef3');     
                	      oldSelection = sel;     
                          w2ui['gridRef<?php echo $this->viewId;?>'].parentId =event.recid;          
                   	}      	                	
                   
                   oldSelection == sel;          
             	 }else {
               	  oldSelection = 0;
                 }
            	//w2ui['gridRef<?php echo $this->viewId;?>'].unlock();
              } 
            },
            
            onDblClick: function (event){ 
            	console.log('dblclick'); 
            	event.onComplete = function () {     
            	 openAddPopup('<?php echo $this->id; ?>','<?php echo $this->parentType; ?>','<?php echo $this->parentId; ?>', 'grid',event.recid,'<?php echo $this->id; ?>', 'edit');   
            	}
            },
            onSelect: function (event) {
             console.log('select');
            // w2ui['gridRef<?php echo $this->viewId;?>'].lock('Loading...', true); 
             event.onComplete = function () {
           	     var sel = w2ui['grid<?php echo $this->viewId;?>'].getSelection();
            	 console.log('select '+sel.length);
              	 if( sel.length > 1 ){
                 	console.log('select');
                   //  w2ui['grid<?php echo $this->viewId;?>'].lock('Loading...', true);
               	  w2ui['gridRef<?php echo $this->viewId;?>'].parentId = null;
                 //   w2ui['grid<?php echo $this->viewId;?>'].unlock();
           		 var sel = w2ui['grid<?php echo $this->viewId;?>'].getSelection();    
           	     // reloadGridData('gridRef', "<?php echo $this->id; ?>",  sel,w2ui['gridRef<?php echo $this->viewId;?>'].objectTypeRef, true );
   	             simpleReloadGridData('gridRef', "<?php echo $this->id; ?>",  sel,w2ui['gridRef<?php echo $this->viewId;?>'].objectTypeRef ); 
           	     
                 cleanGrid('gridRef2');
                 cleanGrid('gridRef3');     

           	    }
              // 	w2ui['gridRef<?php echo $this->viewId;?>'].unlock();
           	 }
            },
            onUnselect : function (event) {
           	 event.onComplete = function () {
             	 var sel = w2ui['grid<?php echo $this->viewId;?>'].getSelection();
               	 if( sel.length > 0 ){
            	 console.log('unselect...');
               // w2ui['gridRef<?php echo $this->viewId;?>'].lock('Loading...', true);
              	                 
            	    var sel = w2ui['grid<?php echo $this->viewId;?>'].getSelection();
         	         simpleReloadGridData('gridRef', "<?php echo $this->id; ?>",  sel,w2ui['gridRef<?php echo $this->viewId;?>'].objectTypeRef ); 
            	    
               	    //reloadGridData('gridRef', "<?php echo $this->id; ?>",  sel,w2ui['gridRef<?php echo $this->viewId;?>'].objectTypeRef, true ); 
                  	cleanGrid('gridRef2');          	  
                  	cleanGrid('gridRef3');     
                 //	w2ui['gridRef<?php echo $this->viewId;?>'].unlock();
              }
               	 }
            },
            onStateSave : function (event) {
                //console.log(event);
                $.ajax({
                    type : 'POST',
                    url: $('#urlAjax').val()+"/savestate",
                    data :  {
                        "view" : "<?php echo $this->viewId;?>",
                        "grid": 'grid',
                        "data" : event.state,
                        "columns" : event.columns
                    },
                    success:$.proxy(function(result){

                    }, this),
                    dataType : 'json'
                });

            }
        },
        formPopup: {
            name: 'formPopup<?php echo $this->viewId;?>',
            focus: -1,
            fields: [],
            actions: []
        },
        form: {
     	    record : [],
            name: 'form<?php echo $this->viewId;?>',
            fields: [],
            focus: -1,
            actions: {
                Reset: function () {
                    this.clear();
                },
                Save: function () {
                    var errors = this.validate();
                    if (errors.length > 0) return;
                    nameOfRel =  "<?php echo $this->id; ?>";
                    if( nameOfRel.match('^get') || nameOfRel.match('^cgt')){
                    	nameOfRel = nameOfRel.substr(3);
                    }
                    $.ajax({
                        type : 'POST',
                        url: $('#urlAjax').val()+"/saveobject",
                        data :  {
                        	"parentId" : "<?php echo $this->parentId; ?>",
                        	"parentType" : ""+"<?php echo $this->parentType; ?>",
                            "objectType" : nameOfRel,
                            "data" : this.record
                        },
                        success:$.proxy(function(result){
                            if(result.success) {
                            	//w2ui.grid.clear();
                                //refresh the page after insert the field
                            	simpleReloadGridData('grid','<?php echo $this->parentType; ?>','<?php echo $this->parentId; ?>','<?php echo $this->id; ?>' ,true);
                                //window.location = window.location;
                            }
                        }, this),
                        dataType : 'json'
                    });

                }
            }
        },
     
    }

    var configPopup = {
            layout: {
                name: 'layoutPopup<?php echo $this->viewId;?>',
                padding: 4,
                panels: [
                    { type: 'right', size: '50%', resizable: true},
                    { type: 'main', minSize: 300 },
                    { type: 'preview',size: '50%' }
                ]
            },
            gridPopup: {
                name: 'gridPopup',
                show: {
                    toolbar            : true,
                    header : true,
                    selectColumn: true,
                    footer    : true
                },
                //autoload: true,
                reorderColumns: true,
                multiSearch : true,
                searches: [{ field: 'recid', caption: 'ID ', type: 'int' }],
                records: [],
                onClick: function(event) {
                    var grid = this;
                    var form = w2ui.formPopup<?php echo $this->viewId;?>;

                    event.onComplete = function () {
                        var sel = grid.getSelection();
                        if (sel.length == 1) {
                            console.log(grid.get(sel[0]));
                            form.recid  = sel[0];
                            objectTypeRef =this.objectTypeRef;
                            parentType = this.parentType;
                            viewId = "<?php echo $this->viewId;?>";
                            $.ajax({
                                type : 'POST',
                              //  url: $('#urlAjax').val()+"/getform?objectType="+parentType+"&viewId="+viewId+"&workspaceId="+"<?php echo $this->sessionHelper()->getWorkspaceId();?>"+"&objectId="+sel[0],
                               // url: $('#urlAjax').val()+"/getform?objectType="+objectTypeRef+"&viewId="+viewId+"&workspaceId="+"<?php echo $this->sessionHelper()->getWorkspaceId();?>"+"&objectId="+sel[0],
                                url: $('#urlAjax').val() + "/getform?objectType=" + objectTypeRef + "&viewId=" + viewId + "&workspaceId=" + "<?php echo $this->sessionHelper()->getWorkspaceId();?>" + "&objectId=" + sel[0]+"&type="+objectTypeRef,
                                    
                                success:$.proxy(function(result){
                               	 console.log(result);
                                    form.record = $.extend(true, {},result);
                                    form.record['recid']=   sel[0];  
                                    form.refresh();
                                }, this),
                                dataType : 'json'
                            });
                        } else {
                            form.clear();
                        }
                    }
                },
                onDelete: function (event) {
                    
                    event.onComplete = function () {
                    	console.log(event);
                        if (event.force) {
                            $.ajax({
                                type : 'POST',
                                url: $('#urlAjax').val()+"/deleteobjects",
                                data :  {
                                    "objectType" : this.objectTypeRef,
                                    "data" : selectedItems
                                },
                                success:$.proxy(function(result){
                                    if(result.success) {
                                        selectedItems = [];
                                        //refresh the page after delete the field
                                        refreshAll();
                                        //window.location = window.location;
                                    }
                                }, this),
                                dataType : 'json'
                            });
                        }
                    }
                },
                onSelect: function (event) {
                    selectedItems.push(event.recid);
                },
                onUnselect : function (event) {
                    var index = selectedItems.indexOf(event.recid);
                    console.log(" index"+index);
                    if (index > -1) {
                    	selectedItems = selectedItems.splice(index, 1);
                    	console.log(selectedItems);
                    }
                },
                onStateSave : function (event) {
                    //console.log(state);
                    $.ajax({
                        type : 'POST',
                        url: $('#urlAjax').val()+"/savestate",
                        data :  {
                            "view" : "<?php echo $this->viewId;?>",
                            "grid": 'gridPopup',
                            "data" : event.state,
                            "columns" : event.columns
                        },
                        success:$.proxy(function(result){

                        }, this),
                        dataType : 'json'
                    });

                }
            },
            gridParentPopup: {
                name: 'gridParentPopup',
                show: {
                    toolbar            : true,
                    header : true,
                    selectColumn: true,
                    footer    : true
                },
                //autoload: true,
                reorderColumns: true,
                multiSearch : true,
                searches: [{ field: 'recid', caption: 'ID ', type: 'int' }],
                onRender: function(event){
               	 var grid = this;

               	 event.onComplete = function () {
                	   if (this.records.length > 0)
              	    	   {
                	    	 grid.click(this.records[0].recid);
             	    	   }
                	   }
                },
                
                onClick: function(event) {
                    var grid = this;


                    event.onComplete = function () {
                        var sel = grid.getSelection();
                        if (sel.length == 1) {
                            console.log(grid.get(sel[0]));
                           
                            objectTypeRef =this.objectTypeRef;
                            objectDestType = this.objectDestType;
                            parentType = this.parentType;
                            viewId = this.viewId;
                            var sel = grid.getSelection();
                            $().w2destroy('formPopup<?php echo $this->viewId;?>'); 
                            
                            initForm('gridPopup', configPopup.form, objectDestType,'layoutPopup'+'<?php echo $this->viewId;?>', "right", objectTypeRef,event.recid, false, null, objectTypeRef, "new", "<?php echo $this->viewId;?>");
                            
                          //  initForm('gridPopup', configPopup.form, objectDestType,'layoutPopup'+'<?php echo $this->viewId;?>', "top", objectTypeRef, event.recid, false, null, null, "edit", viewId);
                            var form = w2ui.formPopup<?php echo $this->viewId;?>;        
                            //refresh the page after delete the field
                           // simpleReloadGridData('gridPopup',parentType, event.recid, objectTypeRef, true);                                   
  
                            $.ajax({
                                type : 'POST',
                                url: $('#urlAjax').val()+"/getMethodResult?objectType="+objectTypeRef+
                                "&methodName=get"+objectDestType+
                                "&id="+event.recid+
                                "&viewId="+"<?php echo $this->viewId?>"+
                                "&gridId="+'gridPopup',
                                success:$.proxy(function(result){
                              	   
                                	w2ui['gridPopup'].records = result.records;
                                	w2ui['gridPopup'].columns = result.columns;
                                	w2ui['gridPopup'].searches = result.searches;
                                    w2ui['gridPopup'].parentType = objectTypeRef;
                                    w2ui['gridPopup'].objectTypeRef = objectDestType;
                                    w2ui['gridPopup'].parentId =event.recid;
                                    w2ui['gridPopup'].viewId = viewId;
                                    w2ui['gridPopup'].url = $('#urlAjax').val()+"/getMethodResult?objectType="+objectTypeRef+
                                    "&methodName=get"+objectDestType+
                                    "&id="+event.recid+
                                    "&viewId="+"<?php echo $this->viewId?>"+
                                    "&gridId="+'gridPopup';
                                    if (! w2ui['gridPopup']) {
                                      w2ui.layoutPopup<?php echo $this->viewId;?>.content('preview', $().w2grid(configPopup.gridPopup));
                                    }
                                    
                               	 w2ui['gridPopup'].reload();
                                	form = w2ui.formPopup<?php echo $this->viewId;?>;  
                             
                                }, this),
                                dataType : 'json'
                            });  
                            form.clear();               
                        } else {
                           form.clear();
                        }
                    }
                },
                onDelete: function (event) {
                    if (event.force) {
                        $.ajax({
                            type : 'POST',
                            url: $('#urlAjax').val()+"/deleteobjects",
                            data :  {
                                "objectType" : "".parentType,
                                "data" : selectedItems
                            },
                            success:$.proxy(function(result){
                                if(result.success) {
                                    selectedItems = [];
                                    //refresh the page after delete the field
                                    refreshAll();
                                    //window.location = window.location;
                                }
                            }, this),
                            dataType : 'json'
                        });
                        
                    }
                },
                onSelect: function (event) {
                    selectedItems.push(event.recid);
                },
                onUnselect : function (event) {
                    var index = selectedItems.indexOf(event.recid);
                    if (index > -1) {
                        selectedItems.splice(index, 1);
                    }
                },
                onStateSave : function (event) {
                    //console.log(state);
                    $.ajax({
                        type : 'POST',
                        url: $('#urlAjax').val()+"/savestate",
                        data :  {
                            "view" : "<?php echo $this->viewId;?>",
                            "grid": 'gridParentPopup',
                            "data" : event.state,
                            "columns" : event.columns
                        },
                        success:$.proxy(function(result){

                        }, this),
                        dataType : 'json'
                    });

                }
            },
            form: {
           	    record : [],
                name: 'formPopup<?php echo $this->viewId;?>',
                fields: [],
                actions: {
                    Reset: function () {
                        this.clear();
                    },
                    Save: function () {


                    }
                }
            }
    }
    

    function refreshAll(){
        //selectedItems = [];
       // selectedRefItems = [];
        //selectedRef2Items = [];
  	  //refresh the page after delete the field
        simpleReloadGridData('grid','<?php echo $this->parentType; ?>', '<?php echo $this->parentId; ?>','<?php echo $this->id; ?>', false);
        //window.location = window.location;
        //refresh the page after delete the field
        simpleReloadGridData('gridRef',w2ui['gridRef<?php echo $this->viewId;?>'].parentType, w2ui['gridRef<?php echo $this->viewId;?>'].parentId,w2ui['gridRef<?php echo $this->viewId;?>'].objectTypeRef, false);
        //window.location = window.location;
        simpleReloadGridData('gridRef2',w2ui['gridRef2<?php echo $this->viewId;?>'].parentType, w2ui['gridRef2<?php echo $this->viewId;?>'].parentId,w2ui['gridRef2<?php echo $this->viewId;?>'].objectTypeRef, false);
        simpleReloadGridData('gridRef3',w2ui['gridRef3<?php echo $this->viewId;?>'].parentType, w2ui['gridRef3<?php echo $this->viewId;?>'].parentId,w2ui['gridRef3<?php echo $this->viewId;?>'].objectTypeRef, false);
        
        if( w2ui['gridPopup'] != undefined && w2ui['gridPopup'].objectTypeRef != undefined ){
        	form = w2ui.formPopup<?php echo $this->viewId;?>;  
        	form.clear();
            simpleReloadGridData('gridPopup',w2ui['gridPopup'].parentType, w2ui['gridPopup'].parentId,w2ui['gridPopup'].objectTypeRef, false, [], true);
            simpleReloadGridData('gridParentPopup',w2ui['gridParentPopup'].parentType, w2ui['gridParentPopup'].parentId,w2ui['gridParentPopup'].objectTypeRef, false, [], true);
            
        }
    }

    function refreshGrid(compShortName){
        compLongName = compShortName + '<?php echo $this->viewId;?>';
          //refresh the page after delete the field
        simpleReloadGridData(compShortName,w2ui[compLongName].parentType, w2ui[compLongName].parentId,w2ui[compLongName].objectTypeRef, false);
    }


    function cleanGrid(compShortName){
    	gridName = compShortName + '<?php echo $this->viewId;?>'
   	    w2ui[gridName].records = [];
    	//w2ui[gridName].columns = [];
  	    //w2ui[gridName].searches = [];
  	    w2ui[gridName].clear();    	
 	    w2ui[gridName].refresh();
    }
    
    $(function () {
        // initialization
        loadList();
    });

    function deleteFromArray(array, indexToDelete){
  	  var remain = new Array();
  	  for(var i in array){
  	    if(array[i] == indexToDelete){
  	      continue;
  	    }
  	    remain.push(array[i]);
  	  }
  	  return remain;
  	}

    function initFormatters() {
    	w2utils.formatters['conditionformatter'] = function (value, params) {
    		if (value == null || value === '') return '';
    		if(value === 'true'){
  			   return '<i class="fa fa-ban text-danger" aria-hidden="true"></i>';
    		} else if(value === 'false'){
   			   return '<i class="fa fa-check-square-o" aria-hidden="true"></i>';
    		}
    		return value;
    	}
    }
    
    function executeMenuAction(event, id, parentId){ 	
     event.menuItem['id']['$id'] = id;   
   	 $.ajax({
         type : 'POST',       
                 
         url:$('#urlAjax').val()+"/execute",

         data :  {
             "parentId" : parentId,
             "parentType" : ""+event.menuItem.parentType,
             "objectType" : ""+event.menuItem.objectType,
             "id" :  event.recid,
             "actionExecution" :event.menuItem.actionExecution,
             "method" :event.menuItem.method,
             "data" :event.menuItem
         },
         success:$.proxy(function(result){
             console.log(result);
             if(result.status == 'success') {   
            	 var actResp = event.menuItem.actionResponse;               
                 //execute action
                 var arrayOfItems = result.items;
            	 for (var prop in arrayOfItems) {
           		  if (arrayOfItems.hasOwnProperty(prop)) { 
           		       // or if (Object.prototype.hasOwnProperty.call(obj,prop)) for safety...
           		       console.log("execute prop: " + prop + " value: " + arrayOfItems[prop]);
             	       var newstr = actResp.replace("%"+prop+"%", arrayOfItems[prop]);
              	       actResp = newstr;
           		  }
           		}
            
                 eval(actResp);    
                 //refresh the page after insert the field
                // reloadGridData(gridName, event.menuItem.parentType ,parentId, event.menuItem.objectType, true);
         	     $().w2popup('close');
           
          } else {
             console.log(result.error);
          }
         }, this),
         dataType : 'json'
     });
    }

    function printDocument(url){
            console.log(" printing "+ url);
    	    win = window.open(url, '', 'width=800, height=500');
    	    win.print(); 
    }

    function openDocument(url){
        console.log(" open "+ url);
	    win = window.open(url, '', 'width=800, height=500');
     }

    function showMessage(message){
        console.log(" show "+ message);
	   alert(message);
     }
    
    function popup(viewId, sourceType,sourceId, parentDestType,objectDestType, methodParent) {
    	console.log('start popup 1 : '+sourceType+" -- "+parentDestType+" -- " + objectDestType);
     	var gridUi = 'gridPopup';
     	$().w2destroy('gridPopup'); 
     	$().w2destroy('gridParentPopup'); 
        var url = $('#urlAjax').val()+"/getMethodResult?objectType="+sourceType+"&methodName="+methodParent+"&id="+sourceId;
        $.ajax({
            type : 'POST',
            url: url,
            success:$.proxy(function(result){
                //$('#main').w2layout(config.layout);

                $('#popup').w2layout(configPopup.layout);

                configPopup.gridParentPopup.records = result.records;
                configPopup.gridParentPopup.columns = result.columns;
              
                var classNameReference = objectDestType;
               // initForm('gridPopup', configPopup.form, objectDestType,'layoutPopup'+'<?php echo $this->viewId;?>', "left", parentDestType,sourceId, false, null, parentDestType, "new", "<?php echo $this->viewId;?>");
                
              //  initForm('gridPopup', config.formPopup , objectDestType,'layoutPopup'+'<?php echo $this->viewId;?>', "left",parentDestType,sourceId,true,null, null, null, "<?php echo $this->viewId;?>");
                
      //          initForm('grid<?php echo $this->viewId;?>', config.form, "<?php echo $this->id; ?>",'layout'+'<?php echo $this->viewId;?>', "main",'<?php echo $this->parentType; ?>','<?php echo $this->parentId; ?>', false, null,null , null,"<?php echo $this->viewId;?>");
                
                 w2popup.open({
                    width: 1000,
                    height: 700,
                    title: 'Popup Title',
                    body: '<div id="popupDiv" style="position: absolute; left: 5px; top: 5px; right: 5px; bottom: 5px;"></div>',//'<div class="w2ui-centered">Click on the "Lock" button or "Lock With a Message" to lock the message for 2 seconds. After 2 seconds it will be automatically unlocked.</div>',
                    buttons: '<button class="btn" >OK</button>',
                    onOpen  : function (event) {
                        event.onComplete = function () {
                            $('#w2ui-popup #popupDiv').w2render('layoutPopup<?php echo $this->viewId;?>');
                            //w2ui.layout.content('left', w2ui.configPopup.gridPopup);
                            w2ui.layoutPopup<?php echo $this->viewId;?>.content('main', $().w2grid(configPopup.gridParentPopup));
                            w2ui.layoutPopup<?php echo $this->viewId;?>.content('preview', $().w2grid(configPopup.gridPopup));

                            //configPopup.gridPopup.searches = result.search;
                            w2ui['gridParentPopup'].objectTypeRef =  parentDestType;
                            w2ui['gridParentPopup'].objectDestType = objectDestType;  
                            w2ui['gridParentPopup'].parentType = sourceType
                            w2ui['gridParentPopup'].parentId = sourceId; 
                           // w2ui['gridPopup<?php echo $this->viewId;?>'].parentId = parentId; 
                            w2ui['gridParentPopup'].viewId = viewId;
                        };
                    },
                    showMax: true
                });

                //  w2ui.layout.content('main', $().w2form(config.form));
            }, this),
            dataType : 'json'
        });

    }
    
    
    function reloadGridData(shortgridName, parentType,parentId, objectType, refresh, searchData ){
        selectedItems = [];
        selectedRefItems = [];
        selectedRef2Items = [];
        var gridName = shortgridName + '<?php echo $this->viewId;?>';
        console.log("reload" + " - "+ gridName+" - "+objectType);
        if( refresh == true ){
     	   w2ui[gridName].clear();
        }
        objectTypeRef = objectType;
        if( objectType.match('^get') || objectType.match('^cgt')){
      	  
         }else{
        	 objectTypeRef = "get"+objectType;
         }
        console.log("reload" + " - "+ refresh);
        w2ui[gridName].lock('Loading...', true);
        $.ajax({
            type : 'POST',
            //url: $('#urlAjax').val()+"/getlist?objectType="+"<?php echo $this->id; ?>"+"&objectId="+"<?php echo $this->objectId; ?>",
             url: $('#urlAjax').val()+"/getMethodResult?objectType="+parentType+"&methodName="+objectTypeRef+"&id="+parentId+"&viewId="+"<?php echo $this->viewId; ?>"+"&gridId="+shortgridName+"&column=true",
             data :  {
                 "searchData" : searchData
             },
             success:$.proxy(function(result){
                 
           	    //$('#main').w2layout(config.layout);  
           	    //w2ui[gridName].records = result.records;
            	w2ui[gridName].columns = result.columns;
            	//if(result.searches){
                console.log(result);
            	w2ui[gridName].searches = result.searches;
            	w2ui[gridName].clear();
            	//}
            	if(refresh == true ){
            		simpleReloadGridData(shortgridName, parentType,parentId, objectType, refresh, searchData );
                  //   w2ui[gridName].reload();
                   
            	} else {
          		  w2ui[gridName].refresh();
            	}
            	w2ui[gridName].unlock();
  
            }, this),
            dataType : 'json'
        });


    }

    function simpleReloadGridData(shortgridName, parentType,parentId, objectType, refresh , searchData, popup  ){
        if(popup){
        	var gridName = shortgridName;
        }else {            
            var gridName = shortgridName + '<?php echo $this->viewId;?>';
        }
        if(  w2ui[gridName] != undefined) {
            console.log("simpleReload" + " - "+ objectType);
        objectTypeRef = objectType;
        

        if( objectType.match('^get') || objectType.match('^cgt')){
      	  
         }else{
        	 objectTypeRef = "get"+objectType;
         }
     	//w2ui[gridName].clear();
       //w2ui[gridName].lock('Loading...', true);
        if( parentId == undefined){    
        	parentId = 0;  
            w2ui[gridName].limit = 0;
        } 
        else{
            w2ui[gridName].limit = 30;
        }
        w2ui[gridName].url= $('#urlAjax').val()+"/getMethodResult?objectType="+parentType+"&methodName="+objectTypeRef+"&id="+parentId+"&viewId="+"<?php echo $this->viewId; ?>"+"&gridId="+shortgridName;
        w2ui[gridName].reload();
        }
        //w2ui[gridName].unlock();
    }

    function resetGridData(shortgridName, parentType,parentId, objectType ){  
        
    	if( objectType.match('^get') || objectType.match('^cgt')){
      	  
        }else{
       	 objectTypeRef = "get"+objectType;
        }
        var gridName = shortgridName + '<?php echo $this->viewId;?>';
     	//w2ui[gridName].clear();
       //w2ui[gridName].lock('Loading...', true);
        if( parentId == undefined){    
        	parentId = 0;  
            w2ui[gridName].limit = 0;
        } 
        else{
            w2ui[gridName].limit = 30;
        }
        //w2ui[gridName].limit = 0;
        w2ui[gridName].url= $('#urlAjax').val()+"/getMethodResult?objectType="+parentType+"&methodName="+objectTypeRef+"&id="+parentId+"&viewId="+"<?php echo $this->viewId; ?>"+"&gridId="+shortgridName;
        w2ui[gridName].reload();
        //w2ui[gridName].unlock();
    }
       
    function overrideLocalStorageStates(result, gridName)
    {
        var states = [];
        if (result.items.length > 0) {
            var columns = {'columns': $.parseJSON(result.items[0].state)};
        } else {
            columns = {'columns' : ''}
        }
        var savedState = $.parseJSON(localStorage.w2ui || '{}');
        if (!savedState.states) savedState.states = {};
        savedState.states[gridName] = columns;
        //savedState.states = states;
        localStorage.w2ui = JSON.stringify(savedState);
        console.log($.parseJSON(localStorage.w2ui));
    }

    function initiateGrid(shortName, gridName, location , configs, id, parentType, header , load , idParent ){
    	var gridMenu = [];
    	var gridUi = gridName;
        $.ajax({
            type : 'POST',
             url: $('#urlAjax').val()+"/getMethodResultListReference?objectType=View&methodName=getComponent[name-"+shortName+"].getContextmenu&id="+"<?php echo $this->viewId; ?>",
           
             success:$.proxy(function(result){
            	if(result.items !== undefined){	
          		   	gridMenu = result.items.slice();       		   	
            	 }
                 var edit = { id: 1, text: 'Edit Item', icon: 'fa-edit' };
         	     var menu = [];
          	     menu.push(edit);
                 var i=2;
                 $.each(gridMenu, function( index, value){
               	    var link = {
                        id: value._id,
                        text: value.link,
                        actionExecution: value.actionExecution,
                        viewId: value.viewId,
                        parentType: value.parentType,
                        objectType:value.objectType,
                        method:value.method,
                        serviceName:value.serviceName,
                        params:value.params,
                        serviceMethod:value.serviceMethod,
                        template:value.template,
                        actionResponse: value.actionResponse,
                        icon: 'fa-edit'
                    }
               	    menu.push(link);
               	});
                configs.menu = menu;
                var objectType = id;
                 if (!w2ui[gridUi]) {
                     console.log(' add grid -'+gridName+ ' for '+objectType);
                    
                    w2ui.layout<?php echo $this->viewId;?>.content(location, $().w2grid(configs));
                 }
               
                 w2ui[gridUi].header = header;    
                 w2ui[gridUi].parentType = parentType;
                 if( objectType.match('^get') || objectType.match('^cgt')){
                	 objectType = objectType.substr(3);
                 }
                 w2ui[gridUi].objectTypeRef = objectType;
                 //if( load ){ 
                 reloadGridData(shortName,parentType,idParent, objectType,load);
                 //}
            }, this),
            dataType : 'json'
        });
       	
    }

    function loadList(){
    	
    	//$().w2destroy('grid<?php echo $this->viewId;?>');  
    	//$().w2destroy('form<?php echo $this->viewId;?>'); 
    	//$().w2destroy('gridRef<?php echo $this->viewId;?>'); 
       	//$().w2destroy('gridRef2<?php echo $this->viewId;?>'); 
    	console.log(w2utils.formatters);
                if(typeof w2ui['layout<?php echo $this->viewId;?>'] === 'undefined')
                {
                	initFormatters();
                	$.ajax({
    	             	headers: {"Authorization": btoa(token)},
        	             url: config.apiUrl + "getMethodResultList?objectType=Menu&methodName=getView&id=" + value.recid + "",
            	         method: 'POST',
                	     
                    	 success: function (dataX) {
                    		 var views = dataX.items;
                    		 var a = new String('<?php echo $this->layout; ?>');
                     	    
                 	        if( a ==  ""){
                    	       $('#main').w2layout(config.layout);
                 	         }else
                 	         {
                    	       $('#layout').w2layout(config.layout);
                    	       w2ui['<?php echo $this->layout; ?>'].content('main',w2ui['layout<?php echo $this->viewId;?>'] );
                 	         }
                 	    
                       	  	 $.each(views, function (indexX, valueX) {
                       			console.log(JSON.stringify(valueX));
                  			 	var dataTag = value.text;
                  			 	var dataLink = valueX.name;
                  			 	var parentType = valueX.parentType;
                   		 		var dataId = valueX.recid;
                   		 	   // localStorage.setItem('view'+value.recid, JSON.stringify(dataX));
                       		 	$.each(dataLink, function(index, value) {
                           		 	//initiateGrid(shortName, gridName, location , configs, id, parentType, header , load , idParent )
                           		 	config.grid.name = "grid"+value.gridShortName+<?php echo $this->viewId;?>';
                           		 	
                              	    initiateGrid(value.gridShortName, config.grid, value.LaoyutLocation , value.gridObject,value.gridRefObject, value.gridRefParentObject , '<?php echo $this->translate(value.gridRefObject); ?>', false, 0);
                           		 	grids.push(value.gridShortName);
                       		 	}
                   		 	});
  	                      }
                	 });
            	      // var typeRef = '<?php echo $this->idRef; ?>';
                                 
                    
               } else{
             

               }
               
                  
                      
                //initiateGrid('gridMenu', 'left' , config.gridMenu, '<?php echo $this->parentType; ?>','<?php echo $this->parentType; ?>', '<?php echo $this->translate($this->parentType); ?>');
                //initForm('grid<?php echo $this->viewId;?>', config.form, "<?php echo $this->id; ?>",'layout'+'<?php echo $this->viewId;?>', "main",'<?php echo $this->parentType; ?>','<?php echo $this->parentId; ?>', false, null, null);
                //initForm('grid', config.form, "<?php echo $this->id; ?>",'layout'+'<?php echo $this->viewId;?>', "main",'<?php echo $this->parentType; ?>','<?php echo $this->parentId; ?>', false, null,null , null,"<?php echo $this->viewId;?>");
                
               // w2ui['layout'+'<?php echo $this->viewId;?>'].hide('left'); 
               // w2ui['layout'+'<?php echo $this->viewId;?>'].hide('main');                                         
        
    	
      //  initForm(config.menu, "menu", "top");

    }

    function initForm(gridName, forms, formName, layoutIn, place, parentType, parentId, popup, selectedId, type, action, viewId){
    	if( formName.match('^get') || formName.match('^cgt')){
    		formName = formName.substr(3);
        }
        if( parentType.match('^get') || parentType.match('^cgt')){
        	parentType = parentType.substr(3);
        }
        
 	   $.ajax({
             type : 'POST',
            // url: $('#urlAjax').val()+"/getdefinition?objectType="+"<?php echo $this->id; ?>"+"&viewId="+
             url:$('#urlAjax').val()+"/getMethodResultList?objectType=View&methodName=getField&id="+viewId+"&objectId="+parentId+"&criteria=object-"+formName+"&type="+parentType+"&action="+action+"&workspaceId=" + "<?php echo $this->sessionHelper()->getWorkspaceId();?>",//+"55fafd8d8f7b68cb190041a9",//&criteria=object-Customer"
                          success:$.proxy(function(result){
               //  $('#main').w2layout(config.layout);
                      var buttons = [];
                      var fields = [];
                    
                      
                      $.each(result.items, function(index, value) {  
                    	   if(value.type == "list" || value.type == "enum"){
                    		    value.options.urlBackup = value.options.url;
                    		    value.options.maxWidth = 100;
                           	    var actionG  = value.group;
                           	    if(actionG.length > 0){
                               	 	 // backup the string!
                                	 value.options.urlBackup = value.options.url;
                               	    
                                   	 var urlStr = value.options.url;
                                	 var res = urlStr.replace("@id@", 0);
                                	 value.options.url = res; 
                               	     
                                     value.options.onRequest = function (event) {
                                       //   console.log('list request1', event);
                                      };
                           	    }
                             	fields.push(value); 
                       	      
                    	   }else if (value.type == "button") {
                              var button = {};
                              var typeTo  = value.object;
                           
                              if( type.match('^get') || type.match('^cgt')){
                            	  type = type.substr(3);
                                }  
                              console.log( "type = "+ type);
                              forms.record['object']= formName; 
                              if( action == "inputForm" ){
                                  typeTo = type;
                                  forms.record['recid']=  selectedId;  
                                  forms.record['object']= type; 
                                  forms.record['parentType']= parentType; 
                                  forms.record['parentId']= parentId; 
                                  forms.record['actionExecution']= action;
                                  forms.record['viewId']= viewId; 
                                  forms.record['componentId']= gridName; 
                              }
                              if( typeTo.match('^get') || typeTo.match('^cgt')){
                            		typeTo = typeTo.substr(3);
                               }
                              button[value.html.caption] = function(){
                                  var formData = new FormData();
                                  var record = jQuery.extend(true, {}, this.record);
                                  //var record = this.record;
                                  $.each(result.items, function(index1, value1) {
                                  	   if(value1.type == "file"){
                                           var name = value1.name;
                                           content = record[name][0].content;
                                           record[name][0]= null;
                                           record[name] = content;
                                  	   }
                            	  });
      

                                $.ajax({
                                    type : 'POST',
                                    cache: false,
                                    url:$('#urlAjax').val()+"/execute",
                                    data :  {
                                        "parentId" : parentId,//"<?php echo $this->parentId; ?>",
                                        "parentType" : ""+parentType,//""+"<?php echo $this->parentType; ?>",
                                        "objectType" : ""+typeTo,//"<?php echo $this->id; ?>",
                                        "id" : this.record['recid'],
                                        "actionExecution" :value.actionExecution,
                                        "method" :value.method,
                                        "data" : record
                                    },
                                    success:$.proxy(function(result){
                                        //console.log(result);
                                        if(result.status == 'success') {     
                                        	  if( popup == true ) {
                                            	  $().w2popup('min');                                            	    
                                               }     
                                               //refresh the page after insert the field
                                               if(value.actionExecution == 'method'){
                                            	   console.log(value);
                                            	   if(value.actionResponse){
                                            	      var actResp = value.actionResponse;               
                                                      //execute action
                                                      var arrayOfItems = result.items;
                                              	      for (var prop in arrayOfItems) {
                                             		     if (arrayOfItems.hasOwnProperty(prop)) { 
                                             		       // or if (Object.prototype.hasOwnProperty.call(obj,prop)) for safety...
                                             		        console.log("execute prop: " + prop + " value: " + arrayOfItems[prop]);
                                               	            var newstr = actResp.replace("@"+prop+"@", arrayOfItems[prop]);
                                                	        actResp = newstr;
                                             		      }
                                              	      }            
                                                       eval(actResp); 
                                            	    }   
                                                    //refresh the page after insert the field
                                                    // reloadGridData(gridName, event.menuItem.parentType ,parentId, event.menuItem.objectType, true);
                                           	         $().w2popup('close');
                                           	    }
                                                else {
                                           	         simpleReloadGridData(gridName, parentType,parentId, value.object, false , false);
                                                }
                                                //refresh the page after delete the field
                                                refreshAll();  //commented because it reloads again a grid and generates an error
                                                if( popup == true) {
                                            	  $().w2popup('close');                                            	    
                                                }                                                                              
                                     } else {
                                        console.log(result.error);
                                     }
                                    }, this),
                                    dataType : 'json'
                                });
                              }
                              buttons = $.extend(buttons, button);
                              //result.items.splice(index, 1);
                          } else {
                             fields.push(value);
                          }
                      });
                      //console.log(fields);
                      forms.header = '<?php echo $this->translate(""); ?>';  
                      //console.log(fields);                      
                      forms.fields = fields;//result.items;
                      forms.actions = buttons;//$.extend([], buttons);
                      forms.onChange = function (event) {
                              //console.log(event);
                              $.each(this.fields, function(index, value) {
                                if (value.type == "list" || value.type == "enum") {
                          	   	  //console.log(value);
                            	      var action  = value.group;
                            	      var actionTo  = value.field;
                            	     
                            	      if(action.length >= 0){
                              	      if (event.target == action) {
                                	    	var nameTo = '#'+actionTo;
                               	    	    //console.log(nameTo);
                                   	    	var $field2 = $(nameTo);                          
                                            var fld = $field2.data('w2field');  //
                                  	    	var field = w2ui[forms.name].get(actionTo);
                                  	    	
                                   	    	var urlStr = field.options.urlBackup;                                   	    
                                   	    	var res = urlStr.replace("@id@", event.value_new._id['$id']);   
                                      	    $field2.data('url', res);
                                      	    fld.options.url = res;
                                        	 
                                            field.options.selected = {};
                                            w2ui[forms.name].record[actionTo] = null; 
                                           // w2ui['form'].refresh();
                                            //w2ui[forms.name].refresh(actionTo);
                                   	    	//console.log("matching1"+res);
                                   	    	$field2.attr('placeholder', '');                                                                      
                                      	    $field2.data('selected', []);
                                      	    $field2.data('url', res);
                                      	    fld.options.url = res;
                                   	    	fld.clearCache();
                                            fld.refresh();
                                   	    	fld.request();
                                   	    }
                            	      }                        	 
                        	        }                  	
                               });
                            };
                       if (action == 'edit') {
                           $.ajax({
                               type: 'POST',
                               url: $('#urlAjax').val() + "/getform?objectType=" + formName + "&viewId=" + viewId + "&workspaceId=" + "<?php echo $this->sessionHelper()->getWorkspaceId();?>" + "&objectId=" + selectedId+"&type="+type,
                               success: $.proxy(function (result) {
                            	   //console.log(fields);
                            	   $.each(fields, function(index, value) {
                                       if (value.type == "list"|| value.type == "enum") {
                                   	      var action  = value.group;
                                   	      if(action.length > 0){
                                       	      var nameField = value.name;
                                          	  //console.log("matching0"+nameField);
                                     	    
                                       	      var urlStr = value.options.urlBackup; 
                                     	      var idRef = result[action]['recid'];  
                                      	      var pos = urlStr.indexOf("@id@");    
                                     	      if( pos > 0  ) {                          	    
                                   	    	    var res = urlStr.replace("@id@", idRef);   
                                     	    	value.options.url = res;  
                                     	      } else {                             	
                                    	    	   value.options.url = urlStr;
                                     	      }
         
                                      	      
                                     	  }
                                     	}
                                   	});
                                  console.log( "EDIT FORM");
                              	  forms.record = $.extend(true, {}, result);  
                                  forms.record['recid']=  selectedId;       
                                  //w2ui[forms.name].refresh();                                  
                               }, this),
                               dataType: 'json'
                           });
                       }
                       
                       if( ! popup){
                    	   console.log(" FORM initinig ");
                    	   
                        	  //console.log(" FORM init ");
                        	  w2ui[layoutIn].content(place, $().w2form(forms));
                    	   
                          }else{
                         	 $().w2popup('open', {
                               title   : '....',
                               body    : '<div id="form" style="width: 100%; height: 100%;"></div>',
                               style   : 'padding: 15px 0px 0px 0px',
                               width   : 500,
                               height  : 300,
                               showMax : true,
                               onToggle: function (event) {
                              	 //$().w2form(forms).hide();
                                   event.onComplete = function () {
                                  	 $().w2form(forms).show();
                                  	 $().w2form(forms).resize();
                                   }
                               },
                               onOpen: function (event) {
                                   event.onComplete = function () {
                                       // specifying an onOpen handler instead is equivalent to specifying an onBeforeOpen handler, which would make this code execute too early and hence not deliver.
                                       $('#w2ui-popup #form').w2render($().w2form(forms).name);

                                   }
                               }
                           });
                      }
             }, this),
             dataType : 'json'
         });

      }
     
    function openPopup (objectId) {
    	//$().w2destroy('foo<?php echo $this->viewId;?>');
        //if (!w2ui.foo<?php echo $this->viewId;?>) {
            $().w2form({
                name: 'foo<?php echo $this->viewId;?>'+objectId,
                style: 'border: 0px; background-color: transparent;',
                formHTML:
               	 '<div class="w2ui-page page-0">'+
                 '    <div class="w2ui-field">'+
                 '        <label>Object:</label>'+
                 '        <div>'+
                 '           <input name="object" type="text" value="<?php echo $this->id; ?>" readonly maxlength="100" style="width: 250px"/>'+
                 '        </div>'+
                 '    </div>'+
                 '    <div class="w2ui-field">'+
                 '        <label>Name:</label>'+
                 '        <div>'+
                 '           <input name="name" type="text" maxlength="100" style="width: 250px"/>'+
                 '        </div>'+
                 '    </div>'+
                 '    <div class="w2ui-field">'+
                 '        <label>Type:</label>'+
                 '        <div>'+
                 '            <select name="type">' +
                 '               <option value="">Select</option>'+
                 '               <option value="list">list</option>'+
                 '               <option value="enum">enum</option>'+
                 '               <option value="ref-by-value">ref-by-value</option>'+
                 '               <option value="ref-by-ref">ref-by-ref</option>'+
                 '               <option value="text">text</option>'+
                 '               <option value="integer">integer</option>'+
                 '               <option value="date">date</option>'+
                 '               <option value="date">time</option>'+
                 '               <option value="datetime">datetime</option>'+
                 '               <option value="checkbox">checkbox</option>'+
                 '               <option value="textarea">textarea</option>'+
                 '               <option value="radio">radio</option>'+
                 '               <option value="alphaNumeric">alphaNumeric</option>'+
                 '               <option value="float">float</option>'+
                 '               <option value="button">button</option>'+
                 '               <option value="color">color</option>'+
                 '            </select>'+
                 '        </div>'+
                 '    </div>'+
                 '    <div class="w2ui-field">'+
                 '        <label>Required:</label>'+
                 '        <div>'+
                 '            <input name="required" type="radio" value="true"> True'+
                 '            <input name="required" type="radio" value="false"> False'+
                 '        </div>'+
                 '    </div>'+
                 '<div class="w2ui-field">'+
                 '        <label>Label:</label>'+
                 '        <div>'+
                 '            <input name="label" type="text" style="width: 250px"/>'+
                 '        </div>'+
                 '    </div>'+
                 '<div class="w2ui-field">'+
                 '        <label>Options:</label>'+
                 '        <div>'+
                 '            <input name="options" type="text" style="width: 250px"/>'+
                 '        </div>'+
                 '    </div>'+ 
                 '<div class="w2ui-field">'+
                 '        <label>Action Exec:</label>'+
                 '        <div>'+
                 '            <input name="actionExecution" type="text" style="width: 250px"/>'+
                 '        </div>'+
                 '    </div>'+
                 '<div class="w2ui-field">'+
                 '        <label>Action Resp:</label>'+
                 '        <div>'+
                 '            <input name="actionResponse" type="text" style="width: 250px"/>'+
                 '        </div>'+
                 '    </div>'+
                 '<div class="w2ui-field">'+
                 '        <label>Reference Type:</label>'+
                 '        <div>'+
                 '            <input name="objectReferenceType" type="text" style="width: 250px"/>'+
                 '        </div>'+
                 '    </div>'+
                 '<div class="w2ui-field">'+
                 '        <label>Method:</label>'+
                 '        <div>'+
                 '            <input name="method" type="text" style="width: 250px"/>'+
                 '        </div>'+
                 '    </div>'+
                 '<div class="w2ui-field">'+
                 '        <label>Group:</label>'+
                 '        <div>'+
                 '            <input name="group" type="text" style="width: 250px"/>'+
                 '        </div>'+
                 '    </div>'+
                 '<div class="w2ui-field">'+
                 '        <label>Searchable:</label>'+
                 '        <div>'+
                 '               <input name="searchable" type="radio" value="true"> True'+
                 '               <input name="searchable" type="radio" value="false"> False'+
                 '        </div>'+
                 '    </div>'+
                 '</div>'+
                 '<div class="w2ui-buttons">'+
                 '    <button class="btn" name="reset">Reset</button>'+
                 '    <button class="btn" name="save">Save</button>'+
                 '</div>',
                 fields: [
                     { field: 'object', type: 'text', required: true },
                     { field: 'name', type: 'text', required: true },
                     { field: 'type', type: 'text', required: true, options: { items: ['', 'text', 'integer', 'date','checkbox'] } },
                     { field: 'required', type: 'radio', required: true},
                     { field: 'label', type: 'text', required: true},
                     { field: 'options', type: 'text', required: false},
                     { field: 'objectReferenceType', type: 'text', required: false},
                     { field: 'actionExecution', type: 'text', required: false},
                     { field: 'actionResponse', type: 'text', required: false},
                     { field: 'method', type: 'text', required: false},
                     { field: 'group', type: 'text', required: false},
                     { field: 'searchable', type: 'text', required: false},
                 ],

                record: { 
                    object    : objectId,
              
                },

                actions: {
                    "save": function () {
                        var errors = this.validate();
                        if (errors.length > 0) return;

                        $.ajax({
                            type : 'POST',
                            url: $('#urlAjax').val()+"/saveobject",
                            data :  {
                                "parentType" : "View",
                                "parentId": ""+"<?php echo $this->viewId;?>",
                                "objectType" : "Field",
                                "data" : this.record
                            },
                            success:$.proxy(function(result){
                                if(result.success) {
                                    fields = result.items;
                                    //refresh the page after insert the field
                                    window.location = window.location;
                                }
                            }, this),
                            dataType : 'json'
                        });
                    },
                    "reset": function () { this.clear(); }
                }
            });
        
        $().w2popup('open', {
            title   : 'Add field',
            body    : '<div id="form" style="width: 100%; height: 100%;"></div>',
            style   : 'padding: 15px 0px 0px 0px',
            width   : 500,
            height  : 300,
            showMax : true,
            onToggle: function (event) {
                $(w2ui.foo<?php echo $this->viewId;?>+objectId.box).hide();
                event.onComplete = function () {
                    $(w2ui.foo<?php echo $this->viewId;?>+objectId.box).show();
                    w2ui.foo<?php echo $this->viewId;?>+objectId.resize();
                }
            },
            onOpen: function (event) {
                event.onComplete = function () {
                    // specifying an onOpen handler instead is equivalent to specifying an onBeforeOpen handler, which would make this code execute too early and hence not deliver.
                    $('#w2ui-popup #form').w2render('foo<?php echo $this->viewId;?>'+objectId);

                }
            }
        });
    }

    function openAddPopup(objectName, parentType, parentId, gridName, selectedId, type, action)
    {
   
        $().w2destroy('formPopup<?php echo $this->viewId;?>'); 
      	var records = [];
      	records['object'] = objectName;
      	config.formPopup.record = $.extend(true, {},records);
        console.log(selectedId);
        initForm(gridName, config.formPopup , objectName,'layout'+'<?php echo $this->viewId;?>', "main",parentType,parentId,true,selectedId, type, action, "<?php echo $this->viewId;?>");
       // w2ui['form<?php echo $this->viewId;?>'].recid = selectedId;
    }

    


</script>



<div id="main" style="width: 100%; height: 400px;"></div>

<div id="popup" style="width: 100%; height: 400px;"></div>

<input type="hidden" name="urlAjax" id="urlAjax"
	value="<?php echo $this->url('home');?>" />

<input type="hidden" name="parentId" id="parentId"
	value="<?php echo $this->parentId; ?>" />

<input type="hidden" name="idObject" id="idObject"
	value="<?php echo $this->id; ?>" />

<input type="hidden" name="parentType" id="parentType"
	value="<?php echo $this->parentType; ?>" />




