
<script type="text/javascript">
var organization ='<?php echo $this->organization;?>';
</script>
<div id="wrapper">
        <div class="w2ui-field">
            <label>Name</label>
        </div>

        <div id="msg-container">

            <div id="messages"></div>
            <input type="text" id="msg" name="msg">
        </div>

        <div class="w2ui-buttons">
            <button type="button" id="send-msg">Send</button>
            <button type="button" id="leave-room">Leave</button>
        </div>
</div>

<script id="messages-template" type="text/x-handlebars-template">
    {{#each messages}}
    <div class="msg">
        <div class="time">{{time}}</div>
        <div class="details">
            <span class="user">{{user}}</span>: <span class="text">{{text}}</span>
        </div>
    </div>
    {{/each}}
</script>

<script type="text/javascript">

  
    $(function () {
        $('#form').w2form({
            name  : 'form',
            url   : 'server/post',
            fields: [
                { field: 'Name', type: 'text', required: true }
            ],
            actions: {
            }
        });
    });
</script>

<?php echo $this->inlineScript()->prependFile($this->basePath() . '/js/chat/main.js') ?>